import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { apiResponse, apiError } from "@/lib/apiResponse";

interface RouteParams {
  params: Promise<{
    id: string;
  }>;
}

// GET /api/tracker/[id]/history - Get edit history of an entry
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return apiError("Unauthorized", 401);
    }

    const { id } = await params;

    // Verify entry belongs to user
    const entry = await prisma.trackerEntry.findFirst({
      where: {
        id,
        userId: session.user.id,
      },
      include: {
        platform: {
          select: {
            id: true,
            name: true,
            slug: true,
            icon: true,
          },
        },
        customPlatform: {
          select: {
            id: true,
            name: true,
            icon: true,
          },
        },
        syncLog: {
          select: {
            id: true,
            status: true,
            startedAt: true,
            completedAt: true,
            triggeredBy: true,
          },
        },
      },
    });

    if (!entry) {
      return apiError("Entry not found", 404);
    }

    // Get audit logs for this entry
    const auditLogs = await prisma.auditLog.findMany({
      where: {
        entityType: "trackerEntry",
        entityId: id,
        userId: session.user.id,
      },
      orderBy: {
        createdAt: "desc",
      },
      take: 50,
    });

    // Build history timeline
    const history: Array<{
      action: string;
      timestamp: Date;
      source: string | null;
      details: Record<string, unknown>;
    }> = [
        {
          action: "CREATED",
          timestamp: entry.createdAt,
          source: entry.source,
          details: {
            isAutoGenerated: entry.isAutoGenerated,
            syncLogId: entry.syncLogId,
          },
        },
      ];

    // Add audit log entries
    auditLogs.forEach((log) => {
      history.push({
        action: log.action,
        timestamp: log.createdAt,
        source: "audit",
        details: {
          changes: log.changes,
          oldValue: log.oldValue,
          newValue: log.newValue,
          ipAddress: log.ipAddress,
        },
      });
    });

    // Add verification if exists
    if (entry.isVerified && entry.verifiedAt) {
      history.push({
        action: "VERIFIED",
        timestamp: entry.verifiedAt,
        source: "verification",
        details: {},
      });
    }

    // Sort by timestamp descending
    history.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

    return apiResponse.success({
      entry: {
        id: entry.id,
        date: entry.date,
        createdAt: entry.createdAt,
        updatedAt: entry.updatedAt,
        source: entry.source,
        isVerified: entry.isVerified,
        verifiedAt: entry.verifiedAt,
        platform: entry.platform,
        customPlatform: entry.customPlatform,
        syncLog: entry.syncLog,
      },
      history,
      totalEvents: history.length,
    });
  } catch (error) {
    console.error("Error fetching entry history:", error);
    return apiError("Failed to fetch entry history", 500);
  }
}
