// src/services/trackerService.ts
import { prisma, paginationArgs, buildPaginationResponse, withTransaction } from "@/lib/prisma";
import { Prisma, PlatformCategory } from "@prisma/client";
import { CacheService } from "@/services/cacheService";
import { updateUserStats } from "@/trigger/user-stats";
import { statsTask } from "@/trigger/stats-task";



// =============================================================================
// TYPES
// =============================================================================

export interface TrackerEntryInput {
  userId: string;
  date: Date;
  platformId?: string | null;
  customPlatformId?: string | null;

  // Classification
  category?: PlatformCategory | null;
  subcategory?: string | null;

  // Primary Metrics
  problemsSolved?: number;
  problemsAttempted?: number;
  easyProblems?: number;
  mediumProblems?: number;
  hardProblems?: number;

  // Code & Development
  commits?: number;
  pullRequests?: number;
  pullRequestsMerged?: number;
  issuesOpened?: number;
  issuesClosed?: number;
  codeReviews?: number;
  linesOfCode?: number;

  // Projects
  projectsStarted?: number;
  projectsCompleted?: number;

  // Learning
  coursesStarted?: number;
  coursesCompleted?: number;
  lessonsCompleted?: number;
  modulesCompleted?: number;
  certificationsEarned?: number;
  quizzesTaken?: number;
  quizzesPassed?: number;

  // Reading & Research
  articlesRead?: number;
  tutorialsCompleted?: number;
  documentationPages?: number;

  // Jobs & Applications
  applicationsSubmitted?: number;
  applicationsViewed?: number;
  interviewsScheduled?: number;
  interviewsCompleted?: number;
  offersReceived?: number;

  // Competitions & Hackathons
  contestsParticipated?: number;
  contestsCompleted?: number;
  hackathonsJoined?: number;
  hackathonsCompleted?: number;

  // Community
  mentoringSessions?: number;
  helpGiven?: number;
  helpReceived?: number;
  postsWritten?: number;
  commentsWritten?: number;

  // Time Tracking
  timeSpent?: number;
  focusTime?: number;

  // Quality Metrics
  averageDifficulty?: number | null;
  accuracyRate?: number | null;
  completionRate?: number | null;

  // Platform-specific
  rating?: number | null;
  ratingChange?: number | null;
  rank?: number | null;
  rankChange?: number | null;
  points?: number | null;
  pointsEarned?: number | null;
  streak?: number | null;
  xpEarned?: number | null;

  // Mood & Notes
  mood?: string | null;
  energyLevel?: number | null;
  productivityRating?: number | null;
  notes?: string | null;

  // Tags & Categories
  tags?: string[];
  topics?: string[];
  languages?: string[];

  // Source & Sync
  source?: string;
  syncLogId?: string | null;
  isAutoGenerated?: boolean;

  // Verification
  isVerified?: boolean;

  // Custom Fields
  customFields?: Record<string, unknown> | null;
}

export type TrackerEntryUpdateInput = Partial<Omit<TrackerEntryInput, "userId">>;

export interface TrackerEntryFilters {
  platformId?: string | null;
  customPlatformId?: string | null;
  category?: PlatformCategory | null;
  categories?: PlatformCategory[];
  source?: string;
  tags?: string[];
  topics?: string[];
  languages?: string[];
  hasMood?: boolean;
  hasNotes?: boolean;
  isVerified?: boolean;
  minProblems?: number;
  minCommits?: number;
  minTimeSpent?: number;
}

export interface TrackerStats {
  // Totals
  totalProblems: number;
  totalCommits: number;
  totalPullRequests: number;
  totalTimeSpent: number;
  totalPoints: number;
  totalDays: number;

  // Difficulty Breakdown
  easyProblems: number;
  mediumProblems: number;
  hardProblems: number;

  // Development
  pullRequestsMerged: number;
  issuesOpened: number;
  issuesClosed: number;
  codeReviews: number;

  // Learning
  coursesCompleted: number;
  certificationsEarned: number;
  lessonsCompleted: number;

  // Applications
  applicationsSubmitted: number;
  interviewsCompleted: number;
  offersReceived: number;

  // Competitions
  contestsParticipated: number;
  hackathonsCompleted: number;

  // Averages
  avgProblemsPerDay: number;
  avgTimePerDay: number;
  avgCommitsPerDay: number;

  // Platform breakdown
  platformBreakdown: Record<
    string,
    {
      problems: number;
      commits: number;
      timeSpent: number;
    }
  >;

  // Category breakdown
  categoryBreakdown: Record<string, number>;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Convert null to Prisma.JsonNull for JSON fields
 */
function toJsonValue(
  value: Record<string, unknown> | null | undefined
): Prisma.InputJsonValue | typeof Prisma.JsonNull | undefined {
  if (value === undefined) return undefined;
  if (value === null) return Prisma.JsonNull;
  return value as Prisma.InputJsonValue;
}

/**
 * Build create data object with proper Prisma types
 */
function buildCreateData(data: TrackerEntryInput): Prisma.TrackerEntryCreateInput {
  return {
    user: { connect: { id: data.userId } },
    date: data.date,

    // Relations - use connect syntax
    ...(data.platformId && { platform: { connect: { id: data.platformId } } }),
    ...(data.customPlatformId && { customPlatform: { connect: { id: data.customPlatformId } } }),
    ...(data.syncLogId && { syncLog: { connect: { id: data.syncLogId } } }),

    // Classification
    category: data.category ?? undefined,
    subcategory: data.subcategory ?? undefined,

    // Primary Metrics
    problemsSolved: data.problemsSolved ?? 0,
    problemsAttempted: data.problemsAttempted ?? 0,
    easyProblems: data.easyProblems ?? 0,
    mediumProblems: data.mediumProblems ?? 0,
    hardProblems: data.hardProblems ?? 0,

    // Code & Development
    commits: data.commits ?? 0,
    pullRequests: data.pullRequests ?? 0,
    pullRequestsMerged: data.pullRequestsMerged ?? 0,
    issuesOpened: data.issuesOpened ?? 0,
    issuesClosed: data.issuesClosed ?? 0,
    codeReviews: data.codeReviews ?? 0,
    linesOfCode: data.linesOfCode ?? 0,

    // Projects
    projectsStarted: data.projectsStarted ?? 0,
    projectsCompleted: data.projectsCompleted ?? 0,

    // Learning
    coursesStarted: data.coursesStarted ?? 0,
    coursesCompleted: data.coursesCompleted ?? 0,
    lessonsCompleted: data.lessonsCompleted ?? 0,
    modulesCompleted: data.modulesCompleted ?? 0,
    certificationsEarned: data.certificationsEarned ?? 0,
    quizzesTaken: data.quizzesTaken ?? 0,
    quizzesPassed: data.quizzesPassed ?? 0,

    // Reading & Research
    articlesRead: data.articlesRead ?? 0,
    tutorialsCompleted: data.tutorialsCompleted ?? 0,
    documentationPages: data.documentationPages ?? 0,

    // Jobs & Applications
    applicationsSubmitted: data.applicationsSubmitted ?? 0,
    applicationsViewed: data.applicationsViewed ?? 0,
    interviewsScheduled: data.interviewsScheduled ?? 0,
    interviewsCompleted: data.interviewsCompleted ?? 0,
    offersReceived: data.offersReceived ?? 0,

    // Competitions & Hackathons
    contestsParticipated: data.contestsParticipated ?? 0,
    contestsCompleted: data.contestsCompleted ?? 0,
    hackathonsJoined: data.hackathonsJoined ?? 0,
    hackathonsCompleted: data.hackathonsCompleted ?? 0,

    // Community
    mentoringSessions: data.mentoringSessions ?? 0,
    helpGiven: data.helpGiven ?? 0,
    helpReceived: data.helpReceived ?? 0,
    postsWritten: data.postsWritten ?? 0,
    commentsWritten: data.commentsWritten ?? 0,

    // Time Tracking
    timeSpent: data.timeSpent ?? 0,
    focusTime: data.focusTime ?? 0,

    // Quality Metrics
    averageDifficulty: data.averageDifficulty ?? undefined,
    accuracyRate: data.accuracyRate ?? undefined,
    completionRate: data.completionRate ?? undefined,

    // Platform-specific
    rating: data.rating ?? undefined,
    ratingChange: data.ratingChange ?? undefined,
    rank: data.rank ?? undefined,
    rankChange: data.rankChange ?? undefined,
    points: data.points ?? undefined,
    pointsEarned: data.pointsEarned ?? undefined,
    streak: data.streak ?? undefined,
    xpEarned: data.xpEarned ?? undefined,

    // Mood & Notes
    mood: data.mood ?? undefined,
    energyLevel: data.energyLevel ?? undefined,
    productivityRating: data.productivityRating ?? undefined,
    notes: data.notes ?? undefined,

    // Tags & Categories
    tags: data.tags ?? [],
    topics: data.topics ?? [],
    languages: data.languages ?? [],

    // Source & Sync
    source: data.source ?? "manual",
    isAutoGenerated: data.isAutoGenerated ?? false,

    // Verification
    isVerified: data.isVerified ?? false,

    // Custom Fields
    customFields: toJsonValue(data.customFields),
  };
}

/**
 * Build update data object with proper Prisma types
 */
function buildUpdateData(data: TrackerEntryUpdateInput): Prisma.TrackerEntryUpdateInput {
  const updateData: Prisma.TrackerEntryUpdateInput = {
    updatedAt: new Date(),
  };

  // Date
  if (data.date !== undefined) {
    const normalizedDate = new Date(data.date);
    normalizedDate.setHours(0, 0, 0, 0);
    updateData.date = normalizedDate;
  }

  // Relations - use connect/disconnect syntax
  if (data.platformId !== undefined) {
    updateData.platform = data.platformId
      ? { connect: { id: data.platformId } }
      : { disconnect: true };
  }
  if (data.customPlatformId !== undefined) {
    updateData.customPlatform = data.customPlatformId
      ? { connect: { id: data.customPlatformId } }
      : { disconnect: true };
  }
  if (data.syncLogId !== undefined) {
    updateData.syncLog = data.syncLogId
      ? { connect: { id: data.syncLogId } }
      : { disconnect: true };
  }

  // Classification
  if (data.category !== undefined) updateData.category = data.category;
  if (data.subcategory !== undefined) updateData.subcategory = data.subcategory;

  // Primary Metrics
  if (data.problemsSolved !== undefined) updateData.problemsSolved = data.problemsSolved;
  if (data.problemsAttempted !== undefined) updateData.problemsAttempted = data.problemsAttempted;
  if (data.easyProblems !== undefined) updateData.easyProblems = data.easyProblems;
  if (data.mediumProblems !== undefined) updateData.mediumProblems = data.mediumProblems;
  if (data.hardProblems !== undefined) updateData.hardProblems = data.hardProblems;

  // Code & Development
  if (data.commits !== undefined) updateData.commits = data.commits;
  if (data.pullRequests !== undefined) updateData.pullRequests = data.pullRequests;
  if (data.pullRequestsMerged !== undefined) updateData.pullRequestsMerged = data.pullRequestsMerged;
  if (data.issuesOpened !== undefined) updateData.issuesOpened = data.issuesOpened;
  if (data.issuesClosed !== undefined) updateData.issuesClosed = data.issuesClosed;
  if (data.codeReviews !== undefined) updateData.codeReviews = data.codeReviews;
  if (data.linesOfCode !== undefined) updateData.linesOfCode = data.linesOfCode;

  // Projects
  if (data.projectsStarted !== undefined) updateData.projectsStarted = data.projectsStarted;
  if (data.projectsCompleted !== undefined) updateData.projectsCompleted = data.projectsCompleted;

  // Learning
  if (data.coursesStarted !== undefined) updateData.coursesStarted = data.coursesStarted;
  if (data.coursesCompleted !== undefined) updateData.coursesCompleted = data.coursesCompleted;
  if (data.lessonsCompleted !== undefined) updateData.lessonsCompleted = data.lessonsCompleted;
  if (data.modulesCompleted !== undefined) updateData.modulesCompleted = data.modulesCompleted;
  if (data.certificationsEarned !== undefined) updateData.certificationsEarned = data.certificationsEarned;
  if (data.quizzesTaken !== undefined) updateData.quizzesTaken = data.quizzesTaken;
  if (data.quizzesPassed !== undefined) updateData.quizzesPassed = data.quizzesPassed;

  // Reading & Research
  if (data.articlesRead !== undefined) updateData.articlesRead = data.articlesRead;
  if (data.tutorialsCompleted !== undefined) updateData.tutorialsCompleted = data.tutorialsCompleted;
  if (data.documentationPages !== undefined) updateData.documentationPages = data.documentationPages;

  // Jobs & Applications
  if (data.applicationsSubmitted !== undefined) updateData.applicationsSubmitted = data.applicationsSubmitted;
  if (data.applicationsViewed !== undefined) updateData.applicationsViewed = data.applicationsViewed;
  if (data.interviewsScheduled !== undefined) updateData.interviewsScheduled = data.interviewsScheduled;
  if (data.interviewsCompleted !== undefined) updateData.interviewsCompleted = data.interviewsCompleted;
  if (data.offersReceived !== undefined) updateData.offersReceived = data.offersReceived;

  // Competitions & Hackathons
  if (data.contestsParticipated !== undefined) updateData.contestsParticipated = data.contestsParticipated;
  if (data.contestsCompleted !== undefined) updateData.contestsCompleted = data.contestsCompleted;
  if (data.hackathonsJoined !== undefined) updateData.hackathonsJoined = data.hackathonsJoined;
  if (data.hackathonsCompleted !== undefined) updateData.hackathonsCompleted = data.hackathonsCompleted;

  // Community
  if (data.mentoringSessions !== undefined) updateData.mentoringSessions = data.mentoringSessions;
  if (data.helpGiven !== undefined) updateData.helpGiven = data.helpGiven;
  if (data.helpReceived !== undefined) updateData.helpReceived = data.helpReceived;
  if (data.postsWritten !== undefined) updateData.postsWritten = data.postsWritten;
  if (data.commentsWritten !== undefined) updateData.commentsWritten = data.commentsWritten;

  // Time Tracking
  if (data.timeSpent !== undefined) updateData.timeSpent = data.timeSpent;
  if (data.focusTime !== undefined) updateData.focusTime = data.focusTime;

  // Quality Metrics
  if (data.averageDifficulty !== undefined) updateData.averageDifficulty = data.averageDifficulty;
  if (data.accuracyRate !== undefined) updateData.accuracyRate = data.accuracyRate;
  if (data.completionRate !== undefined) updateData.completionRate = data.completionRate;

  // Platform-specific
  if (data.rating !== undefined) updateData.rating = data.rating;
  if (data.ratingChange !== undefined) updateData.ratingChange = data.ratingChange;
  if (data.rank !== undefined) updateData.rank = data.rank;
  if (data.rankChange !== undefined) updateData.rankChange = data.rankChange;
  if (data.points !== undefined) updateData.points = data.points;
  if (data.pointsEarned !== undefined) updateData.pointsEarned = data.pointsEarned;
  if (data.streak !== undefined) updateData.streak = data.streak;
  if (data.xpEarned !== undefined) updateData.xpEarned = data.xpEarned;

  // Mood & Notes
  if (data.mood !== undefined) updateData.mood = data.mood;
  if (data.energyLevel !== undefined) updateData.energyLevel = data.energyLevel;
  if (data.productivityRating !== undefined) updateData.productivityRating = data.productivityRating;
  if (data.notes !== undefined) updateData.notes = data.notes;

  // Tags & Categories
  if (data.tags !== undefined) updateData.tags = data.tags;
  if (data.topics !== undefined) updateData.topics = data.topics;
  if (data.languages !== undefined) updateData.languages = data.languages;

  // Source & Sync
  if (data.source !== undefined) updateData.source = data.source;
  if (data.isAutoGenerated !== undefined) updateData.isAutoGenerated = data.isAutoGenerated;

  // Verification
  if (data.isVerified !== undefined) updateData.isVerified = data.isVerified;

  // Custom Fields
  if (data.customFields !== undefined) {
    updateData.customFields = toJsonValue(data.customFields);
  }

  return updateData;
}

// =============================================================================
// TRACKER SERVICE CLASS
// =============================================================================

export class TrackerService {
  // ===========================================================================
  // GET ENTRIES
  // ===========================================================================

  /**
   * Get entries for a date range with filters
   */
  static async getEntries(
    userId: string,
    startDate: Date,
    endDate: Date,
    filters?: TrackerEntryFilters,
    options?: {
      page?: number;
      limit?: number;
      sortBy?: string;
      sortOrder?: "asc" | "desc";
      include?: {
        platform?: boolean;
        customPlatform?: boolean;
        syncLog?: boolean;
      };
      select?: Prisma.TrackerEntrySelect;
    }
  ) {
    const { page = 1, limit = 50, sortBy = "date", sortOrder = "desc", include } = options ?? {};

    // Build where clause
    const where: Prisma.TrackerEntryWhereInput = {
      userId,
      date: {
        gte: startDate,
        lte: endDate,
      },
    };

    // Apply filters
    if (filters) {
      if (filters.platformId) {
        where.platformId = filters.platformId;
      }
      if (filters.customPlatformId) {
        where.customPlatformId = filters.customPlatformId;
      }
      if (filters.category) {
        where.category = filters.category;
      }
      if (filters.categories && filters.categories.length > 0) {
        where.category = { in: filters.categories };
      }
      if (filters.source) {
        where.source = filters.source;
      }
      if (filters.tags && filters.tags.length > 0) {
        where.tags = { hasSome: filters.tags };
      }
      if (filters.topics && filters.topics.length > 0) {
        where.topics = { hasSome: filters.topics };
      }
      if (filters.languages && filters.languages.length > 0) {
        where.languages = { hasSome: filters.languages };
      }
      if (filters.hasMood !== undefined) {
        where.mood = filters.hasMood ? { not: null } : null;
      }
      if (filters.hasNotes !== undefined) {
        where.notes = filters.hasNotes ? { not: null } : null;
      }
      if (filters.isVerified !== undefined) {
        where.isVerified = filters.isVerified;
      }
      if (filters.minProblems !== undefined) {
        where.problemsSolved = { gte: filters.minProblems };
      }
      if (filters.minCommits !== undefined) {
        where.commits = { gte: filters.minCommits };
      }
      if (filters.minTimeSpent !== undefined) {
        where.timeSpent = { gte: filters.minTimeSpent };
      }
    }

    // Get total count
    const total = await prisma.trackerEntry.count({ where });

    // Build include clause
    const includeClause: Prisma.TrackerEntryInclude = {};

    // Default includes if not specified to prevent N+1
    if (!options?.select && !include) {
      includeClause.platform = true;
      includeClause.customPlatform = true;
    } else {
      if (include?.platform) includeClause.platform = true;
      if (include?.customPlatform) includeClause.customPlatform = true;
      if (include?.syncLog) includeClause.syncLog = true;
    }

    // Build findMany arguments
    const findManyArgs: Prisma.TrackerEntryFindManyArgs = {
      where,
      orderBy: { [sortBy]: sortOrder as Prisma.SortOrder },
      ...paginationArgs(page, limit),
    };

    if (options?.select) {
      findManyArgs.select = options.select;
    } else if (Object.keys(includeClause).length > 0) {
      findManyArgs.include = includeClause;
    }

    // Generate cache key for dashboard view (page 1, default sort, no filters)
    const isDashboardView = page === 1 && limit <= 20 && !filters && sortBy === 'date' && sortOrder === 'desc';
    const cacheKey = `tracker:entries:${userId}:dashboard`;

    if (isDashboardView) {
      const cached = await CacheService.get(cacheKey);
      if (cached) return cached;
    }

    // Get entries
    const entries = await prisma.trackerEntry.findMany(findManyArgs);

    const result = buildPaginationResponse(entries, total, page, limit);

    if (isDashboardView) {
      await CacheService.set(cacheKey, result, 60 * 5); // Cache for 5 mins
    }

    return result;
  }

  /**
   * Get all entries for a date range (no pagination)
   */
  static async getAllEntries(
    userId: string,
    startDate: Date,
    endDate: Date,
    platformId?: string | null,
    select?: Prisma.TrackerEntrySelect
  ) {
    const where: Prisma.TrackerEntryWhereInput = {
      userId,
      date: {
        gte: startDate,
        lte: endDate,
      },
    };

    if (platformId) {
      where.platformId = platformId;
    }

    const findManyAllArgs: Prisma.TrackerEntryFindManyArgs = {
      where,
      orderBy: { date: "desc" },
    };

    if (select) {
      findManyAllArgs.select = select;
    } else {
      findManyAllArgs.select = {
        id: true,
        date: true,
        platformId: true,
        customPlatformId: true,
        category: true,
        problemsSolved: true,
        easyProblems: true,
        mediumProblems: true,
        hardProblems: true,
        commits: true,
        pullRequests: true,
        timeSpent: true,
        points: true,
        xpEarned: true,
        rating: true,
        ratingChange: true,
        rank: true,
        source: true,
        isVerified: true,
        createdAt: true,
        updatedAt: true,
        platform: {
          select: { id: true, name: true, slug: true, icon: true, color: true },
        },
        customPlatform: {
          select: { id: true, name: true, icon: true, color: true },
        },
      };
    }

    return prisma.trackerEntry.findMany(findManyAllArgs);
  }

  /**
   * Get entry by ID
   */
  static async getEntryById(id: string, userId?: string) {
    const entry = await prisma.trackerEntry.findUnique({
      where: { id },
      include: {
        platform: true,
        customPlatform: true,
        syncLog: true,
      },
    });

    // Verify ownership if userId provided
    if (entry && userId && entry.userId !== userId) {
      return null;
    }

    return entry;
  }

  /**
   * Get entry for specific date and platform
   */
  static async getEntryByDateAndPlatform(
    userId: string,
    date: Date,
    platformId?: string | null,
    customPlatformId?: string | null
  ) {
    // Normalize date to start of day
    const normalizedDate = new Date(date);
    normalizedDate.setHours(0, 0, 0, 0);

    const where: Prisma.TrackerEntryWhereInput = {
      userId,
      date: normalizedDate,
    };

    if (platformId) {
      where.platformId = platformId;
    } else if (customPlatformId) {
      where.customPlatformId = customPlatformId;
    }

    return prisma.trackerEntry.findFirst({
      where,
      include: {
        platform: true,
        customPlatform: true,
      },
    });
  }

  /**
   * Get entries grouped by date
   */
  static async getEntriesGroupedByDate(
    userId: string,
    startDate: Date,
    endDate: Date
  ): Promise<Map<string, Awaited<ReturnType<typeof prisma.trackerEntry.findMany>>>> {
    const entries = await prisma.trackerEntry.findMany({
      where: {
        userId,
        date: {
          gte: startDate,
          lte: endDate,
        },
      },
      orderBy: { date: "desc" },
      include: {
        platform: true,
      },
    });

    const grouped = new Map<string, typeof entries>();

    for (const entry of entries) {
      const dateKey = entry.date.toISOString().split("T")[0];
      if (!grouped.has(dateKey)) {
        grouped.set(dateKey, []);
      }
      grouped.get(dateKey)!.push(entry);
    }

    return grouped;
  }

  // ===========================================================================
  // CREATE ENTRIES
  // ===========================================================================

  /**
   * Helper to resolve platform ID from ID or Slug
   */
  private static async resolvePlatformId(idOrSlug: string): Promise<string | null> {
    // Optimization: if it looks like a CUID (25 chars, starts with 'c'), maybe skip slug check?
    // But for safety, just check both.
    const platform = await prisma.platform.findFirst({
      where: {
        OR: [
          { id: idOrSlug },
          { slug: idOrSlug }
        ]
      },
      select: { id: true }
    });
    return platform?.id || null;
  }

  // ===========================================================================
  // CREATE ENTRIES
  // ===========================================================================

  /**
   * Create a new tracker entry
   */
  static async createEntry(data: TrackerEntryInput) {
    // Normalize date to start of day
    const normalizedDate = new Date(data.date);
    normalizedDate.setHours(0, 0, 0, 0);

    // Resolve platform ID
    let finalPlatformId = data.platformId;
    if (data.platformId) {
      const resolved = await this.resolvePlatformId(data.platformId);
      if (resolved) {
        finalPlatformId = resolved;
      }
    }

    // Check for existing entry (prevent duplicates)
    if (finalPlatformId) {
      const existing = await prisma.trackerEntry.findFirst({
        where: {
          userId: data.userId,
          date: normalizedDate,
          platformId: finalPlatformId,
        },
      });

      if (existing) {
        throw new Error("Entry already exists for this date and platform");
      }
    }

    // Update date in data
    const entryData = { ...data, date: normalizedDate, platformId: finalPlatformId };

    const entry = await prisma.trackerEntry.create({
      data: buildCreateData(entryData),
      include: {
        platform: true,
        customPlatform: true,
      },
    });

    // Update daily stats
    await this.updateDailyStats(data.userId, normalizedDate);

    // Update user totals (async)
    await updateUserStats.trigger({ userId: data.userId });

    // Invalidate stats cache for this user
    await CacheService.invalidateStats(data.userId);

    return entry;
  }

  /**
   * Create or update entry (upsert)
   */
  static async upsertEntry(data: TrackerEntryInput) {
    const normalizedDate = new Date(data.date);
    normalizedDate.setHours(0, 0, 0, 0);

    // Resolve platform ID
    let finalPlatformId = data.platformId;
    if (data.platformId) {
      const resolved = await this.resolvePlatformId(data.platformId);
      if (resolved) {
        finalPlatformId = resolved;
      }
    }

    // Find existing entry
    const existing = await prisma.trackerEntry.findFirst({
      where: {
        userId: data.userId,
        date: normalizedDate,
        platformId: finalPlatformId,
      },
    });

    if (existing) {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { userId: _userId, ...updateData } = data;
      // Also ensure platformId is the resolved one
      const updatePayload = { ...updateData, platformId: finalPlatformId };
      return this.updateEntry(existing.id, updatePayload, data.userId);
    }

    // Pass the resolved platformId to createEntry 
    // (createEntry will resolve it again, but that's fine/safe, or we can pass modified data)
    return this.createEntry({ ...data, platformId: finalPlatformId });
  }

  /**
   * Bulk create entries
   */
  static async bulkCreateEntries(entries: TrackerEntryInput[]) {
    // Pre-fetch platform map for resolution
    const platforms = await prisma.platform.findMany({ select: { id: true, slug: true } });
    const platformMap = new Map<string, string>();
    platforms.forEach(p => {
      platformMap.set(p.id, p.id);
      platformMap.set(p.slug, p.id);
    });

    const results = await withTransaction(async (tx) => {
      const created = [];

      for (const entry of entries) {
        const normalizedDate = new Date(entry.date);
        normalizedDate.setHours(0, 0, 0, 0);

        let finalPlatformId = entry.platformId;
        if (entry.platformId && platformMap.has(entry.platformId)) {
          finalPlatformId = platformMap.get(entry.platformId);
        }

        const entryData = { ...entry, date: normalizedDate, platformId: finalPlatformId };

        const result = await tx.trackerEntry.create({
          data: buildCreateData(entryData),
        });

        created.push(result);
      }

      return created;
    });

    // Update stats for affected users
    const userIds = [...new Set(entries.map((e) => e.userId))];
    for (const userId of userIds) {
      await updateUserStats.trigger({ userId });
      await CacheService.invalidateStats(userId);
    }

    return results;
  }

  // ===========================================================================
  // UPDATE ENTRIES
  // ===========================================================================

  /**
   * Update an existing entry
   */
  static async updateEntry(id: string, data: TrackerEntryUpdateInput, userId?: string) {
    // Verify ownership if userId provided
    if (userId) {
      const existing = await prisma.trackerEntry.findUnique({
        where: { id },
        select: { userId: true },
      });

      if (!existing || existing.userId !== userId) {
        throw new Error("Entry not found or access denied");
      }
    }

    const entry = await prisma.trackerEntry.update({
      where: { id },
      data: buildUpdateData(data),
      include: {
        platform: true,
        customPlatform: true,
      },
    });

    // Update daily stats
    await this.updateDailyStats(entry.userId, entry.date);

    // Update user totals (async)
    await updateUserStats.trigger({ userId: entry.userId });

    // Invalidate stats cache for this user
    await CacheService.invalidateStats(entry.userId);

    return entry;
  }

  /**
   * Bulk update entries
   */
  static async bulkUpdateEntries(ids: string[], data: TrackerEntryUpdateInput, userId: string) {
    // Verify ownership
    const entries = await prisma.trackerEntry.findMany({
      where: {
        id: { in: ids },
        userId,
      },
      select: { id: true },
    });

    if (entries.length !== ids.length) {
      throw new Error("Some entries not found or access denied");
    }

    // Build update data without relation fields for updateMany
    const updateManyData: Prisma.TrackerEntryUpdateManyMutationInput = {
      updatedAt: new Date(),
    };

    // Only include non-relation fields
    if (data.date !== undefined) {
      const normalizedDate = new Date(data.date);
      normalizedDate.setHours(0, 0, 0, 0);
      updateManyData.date = normalizedDate;
    }
    if (data.category !== undefined) updateManyData.category = data.category;
    if (data.subcategory !== undefined) updateManyData.subcategory = data.subcategory;
    if (data.problemsSolved !== undefined) updateManyData.problemsSolved = data.problemsSolved;
    if (data.commits !== undefined) updateManyData.commits = data.commits;
    if (data.timeSpent !== undefined) updateManyData.timeSpent = data.timeSpent;
    if (data.notes !== undefined) updateManyData.notes = data.notes;
    if (data.tags !== undefined) updateManyData.tags = data.tags;
    if (data.isVerified !== undefined) updateManyData.isVerified = data.isVerified;
    if (data.customFields !== undefined) {
      updateManyData.customFields = toJsonValue(data.customFields);
    }

    await prisma.trackerEntry.updateMany({
      where: {
        id: { in: ids },
        userId,
      },
      data: updateManyData,
    });

    await updateUserStats.trigger({ userId });

    return { updated: ids.length };
  }

  /**
   * Merge entries (combine values from sync with existing)
   */
  static async mergeEntry(
    id: string,
    newData: Partial<TrackerEntryInput>,
    strategy: "replace" | "add" | "max" = "max"
  ) {
    const existing = await prisma.trackerEntry.findUnique({
      where: { id },
    });

    if (!existing) {
      throw new Error("Entry not found");
    }

    const numericFields = [
      "problemsSolved",
      "problemsAttempted",
      "easyProblems",
      "mediumProblems",
      "hardProblems",
      "commits",
      "pullRequests",
      "pullRequestsMerged",
      "issuesOpened",
      "issuesClosed",
      "codeReviews",
      "linesOfCode",
      "projectsStarted",
      "projectsCompleted",
      "coursesStarted",
      "coursesCompleted",
      "lessonsCompleted",
      "modulesCompleted",
      "certificationsEarned",
      "quizzesTaken",
      "quizzesPassed",
      "articlesRead",
      "tutorialsCompleted",
      "documentationPages",
      "applicationsSubmitted",
      "applicationsViewed",
      "interviewsScheduled",
      "interviewsCompleted",
      "offersReceived",
      "contestsParticipated",
      "contestsCompleted",
      "hackathonsJoined",
      "hackathonsCompleted",
      "mentoringSessions",
      "helpGiven",
      "helpReceived",
      "postsWritten",
      "commentsWritten",
      "timeSpent",
      "focusTime",
    ] as const;

    const mergedData: TrackerEntryUpdateInput = {};

    for (const field of numericFields) {
      const existingValue = (existing as Record<string, unknown>)[field] as number ?? 0;
      const newValue = (newData as Record<string, unknown>)[field] as number | undefined;

      if (newValue !== undefined) {
        switch (strategy) {
          case "replace":
            (mergedData as Record<string, unknown>)[field] = newValue;
            break;
          case "add":
            (mergedData as Record<string, unknown>)[field] = existingValue + newValue;
            break;
          case "max":
            (mergedData as Record<string, unknown>)[field] = Math.max(existingValue, newValue);
            break;
        }
      }
    }

    // Merge arrays (tags, topics, languages)
    if (newData.tags) {
      mergedData.tags = [...new Set([...existing.tags, ...newData.tags])];
    }
    if (newData.topics) {
      mergedData.topics = [...new Set([...existing.topics, ...newData.topics])];
    }
    if (newData.languages) {
      mergedData.languages = [...new Set([...existing.languages, ...newData.languages])];
    }

    // Non-numeric fields (replace if provided)
    if (newData.notes && !existing.notes) {
      mergedData.notes = newData.notes;
    }
    if (newData.mood) {
      mergedData.mood = newData.mood;
    }
    if (newData.rating !== undefined) {
      mergedData.rating = newData.rating;
    }
    if (newData.rank !== undefined) {
      mergedData.rank = newData.rank;
    }

    return this.updateEntry(id, mergedData);
  }

  // ===========================================================================
  // DELETE ENTRIES
  // ===========================================================================

  /**
   * Delete an entry
   */
  static async deleteEntry(id: string, userId?: string) {
    // Get entry to verify ownership and get date for stats update
    const entry = await prisma.trackerEntry.findUnique({
      where: { id },
      select: { userId: true, date: true },
    });

    if (!entry) {
      throw new Error("Entry not found");
    }

    if (userId && entry.userId !== userId) {
      throw new Error("Access denied");
    }

    await prisma.trackerEntry.delete({
      where: { id },
    });

    // Update daily stats
    await this.updateDailyStats(entry.userId, entry.date);

    // Update user totals (async)
    await updateUserStats.trigger({ userId: entry.userId });

    // Invalidate stats cache for this user
    await CacheService.invalidateStats(entry.userId);

    return { deleted: true };
  }

  /**
   * Bulk delete entries
   */
  static async bulkDeleteEntries(ids: string[], userId: string) {
    // Verify ownership
    const entries = await prisma.trackerEntry.findMany({
      where: {
        id: { in: ids },
        userId,
      },
      select: { id: true, date: true },
    });

    if (entries.length === 0) {
      throw new Error("No entries found or access denied");
    }

    const deletedCount = await prisma.trackerEntry.deleteMany({
      where: {
        id: { in: entries.map((e) => e.id) },
        userId,
      },
    });

    // Update stats for affected dates
    const dates = [...new Set(entries.map((e) => e.date.toISOString().split("T")[0]))];
    for (const dateStr of dates) {
      await this.updateDailyStats(userId, new Date(dateStr));
    }

    await updateUserStats.trigger({ userId });

    // Invalidate stats cache for this user
    await CacheService.invalidateStats(userId);

    return { deleted: deletedCount.count };
  }

  /**
   * Delete entries by date range
   */
  static async deleteEntriesByDateRange(
    userId: string,
    startDate: Date,
    endDate: Date,
    platformId?: string
  ) {
    const where: Prisma.TrackerEntryWhereInput = {
      userId,
      date: {
        gte: startDate,
        lte: endDate,
      },
    };

    if (platformId) {
      where.platformId = platformId;
    }

    const result = await prisma.trackerEntry.deleteMany({ where });

    await updateUserStats.trigger({ userId });

    // Invalidate stats cache for this user
    await CacheService.invalidateStats(userId);

    return { deleted: result.count };
  }

  // ===========================================================================
  // STATISTICS
  // ===========================================================================

  /**
   * Get comprehensive statistics for a date range
   */
  static async getStats(
    userId: string,
    startDate: Date,
    endDate: Date,
    platformId?: string | null
  ): Promise<TrackerStats> {
    const where: Prisma.TrackerEntryWhereInput = {
      userId,
      date: {
        gte: startDate,
        lte: endDate,
      },
    };

    if (platformId) {
      where.platformId = platformId;
    }

    // Get aggregates
    const aggregates = await prisma.trackerEntry.aggregate({
      where,
      _sum: {
        problemsSolved: true,
        problemsAttempted: true,
        easyProblems: true,
        mediumProblems: true,
        hardProblems: true,
        commits: true,
        pullRequests: true,
        pullRequestsMerged: true,
        issuesOpened: true,
        issuesClosed: true,
        codeReviews: true,
        coursesCompleted: true,
        certificationsEarned: true,
        lessonsCompleted: true,
        applicationsSubmitted: true,
        interviewsCompleted: true,
        offersReceived: true,
        contestsParticipated: true,
        hackathonsCompleted: true,
        timeSpent: true,
        points: true,
        pointsEarned: true,
      },
      _count: {
        id: true,
      },
    });

    // Get distinct days
    const distinctDays = await prisma.trackerEntry.findMany({
      where,
      select: { date: true },
      distinct: ["date"],
    });

    const totalDays = distinctDays.length;

    // Get platform breakdown
    const platformBreakdown: Record<string, { problems: number; commits: number; timeSpent: number }> =
      {};

    const platformAggregates = await prisma.trackerEntry.groupBy({
      by: ["platformId"],
      where: {
        ...where,
        platformId: { not: null },
      },
      _sum: {
        problemsSolved: true,
        commits: true,
        timeSpent: true,
      },
    });

    for (const pa of platformAggregates) {
      if (pa.platformId) {
        platformBreakdown[pa.platformId] = {
          problems: pa._sum.problemsSolved ?? 0,
          commits: pa._sum.commits ?? 0,
          timeSpent: pa._sum.timeSpent ?? 0,
        };
      }
    }

    // Get category breakdown
    const categoryBreakdown: Record<string, number> = {};

    const categoryAggregates = await prisma.trackerEntry.groupBy({
      by: ["category"],
      where: {
        ...where,
        category: { not: null },
      },
      _sum: {
        problemsSolved: true,
      },
    });

    for (const ca of categoryAggregates) {
      if (ca.category) {
        categoryBreakdown[ca.category] = ca._sum.problemsSolved ?? 0;
      }
    }

    const totalProblems = aggregates._sum.problemsSolved ?? 0;
    const totalCommits = aggregates._sum.commits ?? 0;
    const totalTimeSpent = aggregates._sum.timeSpent ?? 0;

    return {
      // Totals
      totalProblems,
      totalCommits,
      totalPullRequests: aggregates._sum.pullRequests ?? 0,
      totalTimeSpent,
      totalPoints: (aggregates._sum.points ?? 0) + (aggregates._sum.pointsEarned ?? 0),
      totalDays,

      // Difficulty Breakdown
      easyProblems: aggregates._sum.easyProblems ?? 0,
      mediumProblems: aggregates._sum.mediumProblems ?? 0,
      hardProblems: aggregates._sum.hardProblems ?? 0,

      // Development
      pullRequestsMerged: aggregates._sum.pullRequestsMerged ?? 0,
      issuesOpened: aggregates._sum.issuesOpened ?? 0,
      issuesClosed: aggregates._sum.issuesClosed ?? 0,
      codeReviews: aggregates._sum.codeReviews ?? 0,

      // Learning
      coursesCompleted: aggregates._sum.coursesCompleted ?? 0,
      certificationsEarned: aggregates._sum.certificationsEarned ?? 0,
      lessonsCompleted: aggregates._sum.lessonsCompleted ?? 0,

      // Applications
      applicationsSubmitted: aggregates._sum.applicationsSubmitted ?? 0,
      interviewsCompleted: aggregates._sum.interviewsCompleted ?? 0,
      offersReceived: aggregates._sum.offersReceived ?? 0,

      // Competitions
      contestsParticipated: aggregates._sum.contestsParticipated ?? 0,
      hackathonsCompleted: aggregates._sum.hackathonsCompleted ?? 0,

      // Averages
      avgProblemsPerDay: totalDays > 0 ? totalProblems / totalDays : 0,
      avgTimePerDay: totalDays > 0 ? totalTimeSpent / totalDays : 0,
      avgCommitsPerDay: totalDays > 0 ? totalCommits / totalDays : 0,

      // Breakdowns
      platformBreakdown,
      categoryBreakdown,
    };
  }

  /**
   * Get heatmap data for calendar visualization
   */
  static async getHeatmapData(
    userId: string,
    year: number
  ): Promise<{ date: string; count: number; level: number }[]> {
    const startDate = new Date(year, 0, 1);
    const endDate = new Date(year, 11, 31);

    const dailyStats = await prisma.trackerEntry.groupBy({
      by: ["date"],
      where: {
        userId,
        date: {
          gte: startDate,
          lte: endDate,
        },
      },
      _sum: {
        problemsSolved: true,
        commits: true,
      },
    });

    // Find max activity for level calculation
    const maxActivity = Math.max(
      ...dailyStats.map((d) => (d._sum.problemsSolved ?? 0) + (d._sum.commits ?? 0)),
      1
    );

    return dailyStats.map((day) => {
      const count = (day._sum.problemsSolved ?? 0) + (day._sum.commits ?? 0);
      const level = count === 0 ? 0 : Math.ceil((count / maxActivity) * 4);

      return {
        date: day.date.toISOString().split("T")[0],
        count,
        level: Math.min(level, 4),
      };
    });
  }

  /**
   * Get streak information
   */
  static async getStreakInfo(userId: string): Promise<{
    current: number;
    longest: number;
    lastActivityDate: Date | null;
    streakDates: string[];
  }> {
    // Get all distinct activity dates
    const entries = await prisma.trackerEntry.findMany({
      where: { userId },
      orderBy: { date: "desc" },
      select: { date: true },
      distinct: ["date"],
    });

    if (entries.length === 0) {
      return {
        current: 0,
        longest: 0,
        lastActivityDate: null,
        streakDates: [],
      };
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const dates = entries.map((e) => {
      const d = new Date(e.date);
      d.setHours(0, 0, 0, 0);
      return d;
    });

    // Calculate current streak
    let currentStreak = 0;
    const streakDates: string[] = [];

    for (let i = 0; i < dates.length; i++) {
      const expectedDate = new Date(today);
      expectedDate.setDate(expectedDate.getDate() - currentStreak);
      expectedDate.setHours(0, 0, 0, 0);

      const diffDays = Math.floor(
        (expectedDate.getTime() - dates[i].getTime()) / (1000 * 60 * 60 * 24)
      );

      if (i === 0 && diffDays > 1) {
        break;
      }

      if (diffDays === 0 || (i === 0 && diffDays === 1)) {
        currentStreak++;
        streakDates.push(dates[i].toISOString().split("T")[0]);
      } else {
        break;
      }
    }

    // Calculate longest streak
    let longestStreak = 0;
    let tempStreak = 0;

    for (let i = 0; i < dates.length; i++) {
      if (i === 0) {
        tempStreak = 1;
      } else {
        const diffDays = Math.floor(
          (dates[i - 1].getTime() - dates[i].getTime()) / (1000 * 60 * 60 * 24)
        );

        if (diffDays === 1) {
          tempStreak++;
        } else {
          longestStreak = Math.max(longestStreak, tempStreak);
          tempStreak = 1;
        }
      }
    }
    longestStreak = Math.max(longestStreak, tempStreak);

    return {
      current: currentStreak,
      longest: longestStreak,
      lastActivityDate: dates[0] || null,
      streakDates,
    };
  }

  // ===========================================================================
  // DAILY STATS
  // ===========================================================================

  /**
   * Queue daily stats update
   */
  static async updateDailyStats(userId: string, date: Date) {
    try {
      await statsTask.trigger({
        userId,
        date: date.toISOString(),
        type: "daily-stats",
      });
    } catch (error) {
      // Fallback to inline update if Trigger.dev fails
      console.error('Failed to trigger stats task, running inline', error);
      await this.processDailyStats(userId, date);
    }
  }

  /**
   * Process daily stats update (Logic moved from updateDailyStats)
   * This is called by the worker
   */
  /**
   * Process daily stats update (Logic moved from updateDailyStats)
   * This is called by the worker
   */
  static async processDailyStats(userId: string, date: Date) {
    const normalizedDate = new Date(date);
    normalizedDate.setHours(0, 0, 0, 0);

    // Calculate totals using aggregate
    const aggregates = await prisma.trackerEntry.aggregate({
      where: {
        userId,
        date: normalizedDate,
      },
      _sum: {
        problemsSolved: true,
        commits: true,
        pullRequests: true,
        timeSpent: true,
        points: true,
        pointsEarned: true,
      },
    });

    // Calculate breakdowns using groupBy
    const platformStats = await prisma.trackerEntry.groupBy({
      by: ['platformId'],
      where: {
        userId,
        date: normalizedDate,
        platformId: { not: null },
      },
      _sum: {
        problemsSolved: true,
        commits: true,
      },
    });

    const categoryStats = await prisma.trackerEntry.groupBy({
      by: ['category'],
      where: {
        userId,
        date: normalizedDate,
        category: { not: null },
      },
      _sum: {
        problemsSolved: true,
      },
    });

    // Build platform breakdown
    const platformBreakdown: Record<string, { problems: number; commits: number }> = {};
    for (const stat of platformStats) {
      if (stat.platformId) {
        platformBreakdown[stat.platformId] = {
          problems: stat._sum.problemsSolved ?? 0,
          commits: stat._sum.commits ?? 0,
        };
      }
    }

    // Build category breakdown
    const categoryBreakdown: Record<string, number> = {};
    for (const stat of categoryStats) {
      if (stat.category) {
        // category is an enum, ensuring string key
        categoryBreakdown[stat.category] = stat._sum.problemsSolved ?? 0;
      }
    }

    const totals = {
      totalProblems: aggregates._sum.problemsSolved ?? 0,
      totalCommits: aggregates._sum.commits ?? 0,
      totalPullRequests: aggregates._sum.pullRequests ?? 0,
      totalTimeSpent: aggregates._sum.timeSpent ?? 0,
      totalPoints: (aggregates._sum.points ?? 0) + (aggregates._sum.pointsEarned ?? 0),
    };

    const hadActivity =
      totals.totalProblems > 0 || totals.totalCommits > 0 || totals.totalTimeSpent > 0;

    // Upsert daily stats
    await prisma.dailyStats.upsert({
      where: {
        userId_date: {
          userId,
          date: normalizedDate,
        },
      },
      create: {
        userId,
        date: normalizedDate,
        ...totals,
        platformBreakdown: platformBreakdown as Prisma.InputJsonValue,
        categoryBreakdown: categoryBreakdown as Prisma.InputJsonValue,
        hadActivity,
        isComplete: true,
        computedAt: new Date(),
      },
      update: {
        ...totals,
        platformBreakdown: platformBreakdown as Prisma.InputJsonValue,
        categoryBreakdown: categoryBreakdown as Prisma.InputJsonValue,
        hadActivity,
        isComplete: true,
        computedAt: new Date(),
        updatedAt: new Date(),
      },
    });
  }

  /**
   * Get daily stats for a date range
   */
  static async getDailyStats(userId: string, startDate: Date, endDate: Date) {
    return prisma.dailyStats.findMany({
      where: {
        userId,
        date: {
          gte: startDate,
          lte: endDate,
        },
      },
      orderBy: { date: "desc" },
    });
  }

  // ===========================================================================
  // USER TOTALS
  // ===========================================================================


  // ===========================================================================
  // IMPORT / EXPORT
  // ===========================================================================

  /**
   * Export entries to plain object format
   */
  static async exportEntries(
    userId: string,
    startDate: Date,
    endDate: Date,
    format: "full" | "summary" = "full"
  ) {
    const entries = await this.getAllEntries(userId, startDate, endDate);

    if (format === "summary") {
      return entries.map((entry) => ({
        date: entry.date.toISOString().split("T")[0],
        platform: (entry.platformId as { name?: string })?.name ?? "Custom",
        problemsSolved: entry.problemsSolved,
        commits: entry.commits,
        timeSpent: entry.timeSpent,
        notes: entry.notes,
      }));
    }

    return entries;
  }

  /**
   * Validate import data
   */
  static validateImportData(data: unknown[]): {
    valid: TrackerEntryInput[];
    errors: { row: number; error: string }[];
  } {
    const valid: TrackerEntryInput[] = [];
    const errors: { row: number; error: string }[] = [];

    for (let i = 0; i < data.length; i++) {
      const row = data[i] as Record<string, unknown>;

      // Required fields
      if (!row.date) {
        errors.push({ row: i + 1, error: "Missing required field: date" });
        continue;
      }

      // Validate date
      const date = new Date(row.date as string);
      if (isNaN(date.getTime())) {
        errors.push({ row: i + 1, error: "Invalid date format" });
        continue;
      }

      // Build valid entry
      const entry: Partial<TrackerEntryInput> = {
        date,
        userId: "", // Will be set during import
      };

      // Map numeric fields
      const numericFields = [
        "problemsSolved",
        "commits",
        "timeSpent",
        "easyProblems",
        "mediumProblems",
        "hardProblems",
      ];

      for (const field of numericFields) {
        if (row[field] !== undefined) {
          const value = Number(row[field]);
          if (!isNaN(value) && value >= 0) {
            (entry as Record<string, unknown>)[field] = value;
          }
        }
      }

      // Map string fields
      if (row.notes && typeof row.notes === "string") {
        entry.notes = row.notes;
      }
      if (row.platformId && typeof row.platformId === "string") {
        entry.platformId = row.platformId;
      }

      // Map array fields
      if (Array.isArray(row.tags)) {
        entry.tags = row.tags.filter((t): t is string => typeof t === "string");
      }

      valid.push(entry as TrackerEntryInput);
    }

    return { valid, errors };
  }

  // ===========================================================================
  // DUPLICATES
  // ===========================================================================

  /**
   * Duplicate an entry to another date
   */
  static async duplicateEntry(id: string, newDate: Date, userId: string) {
    const original = await this.getEntryById(id, userId);

    if (!original) {
      throw new Error("Entry not found or access denied");
    }

    const entryData: TrackerEntryInput = {
      userId,
      date: newDate,
      platformId: original.platformId,
      customPlatformId: original.customPlatformId,
      category: original.category,
      subcategory: original.subcategory,
      problemsSolved: original.problemsSolved,
      problemsAttempted: original.problemsAttempted,
      easyProblems: original.easyProblems,
      mediumProblems: original.mediumProblems,
      hardProblems: original.hardProblems,
      commits: original.commits,
      pullRequests: original.pullRequests,
      pullRequestsMerged: original.pullRequestsMerged,
      issuesOpened: original.issuesOpened,
      issuesClosed: original.issuesClosed,
      codeReviews: original.codeReviews,
      linesOfCode: original.linesOfCode,
      projectsStarted: original.projectsStarted,
      projectsCompleted: original.projectsCompleted,
      coursesStarted: original.coursesStarted,
      coursesCompleted: original.coursesCompleted,
      lessonsCompleted: original.lessonsCompleted,
      modulesCompleted: original.modulesCompleted,
      certificationsEarned: original.certificationsEarned,
      quizzesTaken: original.quizzesTaken,
      quizzesPassed: original.quizzesPassed,
      articlesRead: original.articlesRead,
      tutorialsCompleted: original.tutorialsCompleted,
      documentationPages: original.documentationPages,
      applicationsSubmitted: original.applicationsSubmitted,
      applicationsViewed: original.applicationsViewed,
      interviewsScheduled: original.interviewsScheduled,
      interviewsCompleted: original.interviewsCompleted,
      offersReceived: original.offersReceived,
      contestsParticipated: original.contestsParticipated,
      contestsCompleted: original.contestsCompleted,
      hackathonsJoined: original.hackathonsJoined,
      hackathonsCompleted: original.hackathonsCompleted,
      mentoringSessions: original.mentoringSessions,
      helpGiven: original.helpGiven,
      helpReceived: original.helpReceived,
      postsWritten: original.postsWritten,
      commentsWritten: original.commentsWritten,
      timeSpent: original.timeSpent,
      focusTime: original.focusTime,
      averageDifficulty: original.averageDifficulty,
      accuracyRate: original.accuracyRate,
      completionRate: original.completionRate,
      rating: original.rating,
      ratingChange: original.ratingChange,
      rank: original.rank,
      rankChange: original.rankChange,
      points: original.points,
      pointsEarned: original.pointsEarned,
      streak: original.streak,
      xpEarned: original.xpEarned,
      mood: original.mood,
      energyLevel: original.energyLevel,
      productivityRating: original.productivityRating,
      notes: original.notes,
      tags: original.tags,
      topics: original.topics,
      languages: original.languages,
      source: "duplicate",
      isAutoGenerated: false,
      isVerified: false,
      customFields: original.customFields as Record<string, unknown> | null,
    };

    return this.createEntry(entryData);
  }
}

// =============================================================================
// EXPORT
// =============================================================================

export default TrackerService;