// src/services/trackerImportService.ts
import { prisma } from '@/lib/prisma';
import { logger } from '@/lib/logger';
import { PlatformCategory, Prisma } from '@prisma/client';
import Papa from 'papaparse';

const log = logger.child({ service: 'TrackerImportService' });

export interface ImportData {
  date: string;
  platform?: string;
  category?: string;
  problemsSolved?: number;
  commits?: number;
  timeSpent?: number;
  notes?: string;
  [key: string]: unknown;
}

export interface ImportResult {
  success: boolean;
  imported: number;
  updated: number;
  failed: number;
  errors: Array<{ row: number; error: string }>;
}

class TrackerImportService {
  /**
   * Import from CSV
   */
  async importFromCSV(userId: string, csvContent: string): Promise<ImportResult> {
    try {
      const parsed = Papa.parse<ImportData>(csvContent, {
        header: true,
        skipEmptyLines: true,
        transformHeader: (header) => header.trim().toLowerCase(),
      });

      if (parsed.errors.length > 0) {
        log.error('CSV parse errors', { userId, errors: parsed.errors });
        throw new Error('Invalid CSV format');
      }

      return this.importData(userId, parsed.data);
    } catch (error) {
      log.error('Error importing from CSV', { userId }, error);
      throw error;
    }
  }

  /**
   * Import from JSON
   */
  async importFromJSON(userId: string, jsonContent: string): Promise<ImportResult> {
    try {
      const data = JSON.parse(jsonContent) as ImportData[];

      if (!Array.isArray(data)) {
        throw new Error('JSON must be an array of entries');
      }

      return this.importData(userId, data);
    } catch (error) {
      log.error('Error importing from JSON', { userId }, error);
      throw error;
    }
  }

  /**
   * Import data array
   */
  private async importData(userId: string, data: ImportData[]): Promise<ImportResult> {
    try {
      let imported = 0;
      let updated = 0;
      let failed = 0;
      const errors: Array<{ row: number; error: string }> = [];

      for (let i = 0; i < data.length; i++) {
        const row = data[i];

        try {
          const validated = this.validateRow(row);

          if (!validated.valid) {
            errors.push({ row: i + 1, error: validated.error || 'Invalid data' });
            failed++;
            continue;
          }

          const date = new Date(row.date);
          date.setHours(0, 0, 0, 0);

          // Check if entry exists
          const existing = await prisma.trackerEntry.findFirst({
            where: {
              userId,
              date,
              platformId: null, // Import entries are manual
            },
          });

          const entryData: Prisma.TrackerEntryCreateInput = {
            user: { connect: { id: userId } },
            date,
            category: this.parseCategory(row.category),
            problemsSolved: this.parseNumber(row.problemsSolved),
            commits: this.parseNumber(row.commits),
            timeSpent: this.parseNumber(row.timeSpent),
            notes: row.notes || null,
            source: 'import',
            isAutoGenerated: false,
          };

          if (existing) {
            await prisma.trackerEntry.update({
              where: { id: existing.id },
              data: {
                problemsSolved: entryData.problemsSolved,
                commits: entryData.commits,
                timeSpent: entryData.timeSpent,
                notes: entryData.notes,
                category: entryData.category,
              },
            });
            updated++;
          } else {
            await prisma.trackerEntry.create({
              data: entryData,
            });
            imported++;
          }
        } catch (error) {
          errors.push({
            row: i + 1,
            error: error instanceof Error ? error.message : 'Unknown error',
          });
          failed++;
        }
      }

      log.info('Data imported', { userId, imported, updated, failed });

      return {
        success: failed === 0,
        imported,
        updated,
        failed,
        errors,
      };
    } catch (error) {
      log.error('Error importing data', { userId }, error);
      throw error;
    }
  }

  /**
   * Validate import row
   */
  private validateRow(row: ImportData): { valid: boolean; error?: string } {
    if (!row.date) {
      return { valid: false, error: 'Date is required' };
    }

    const date = new Date(row.date);
    if (isNaN(date.getTime())) {
      return { valid: false, error: 'Invalid date format' };
    }

    return { valid: true };
  }

  /**
   * Parse number safely
   */
  private parseNumber(value: unknown): number {
    if (value === null || value === undefined || value === '') {
      return 0;
    }

    const num = Number(value);
    return isNaN(num) ? 0 : Math.max(0, num);
  }

  /**
   * Parse category
   */
  private parseCategory(value: unknown): PlatformCategory | null {
    if (!value || typeof value !== 'string') {
      return null;
    }

    const normalized = value.toUpperCase().replace(/[^A-Z_]/g, '_');
    const categories: PlatformCategory[] = [
      'DSA',
      'JOB',
      'GIT',
      'LEARNING',
      'HACKATHON',
      'OPENSOURCE',
      'COMPANY',
      'DESIGN',
      'DATA_SCIENCE',
      'OTHER',
    ];

    return categories.includes(normalized as PlatformCategory)
      ? (normalized as PlatformCategory)
      : null;
  }

  /**
   * Export template CSV
   */
  getTemplateCSV(): string {
    const headers = [
      'date',
      'category',
      'problemsSolved',
      'commits',
      'timeSpent',
      'notes',
    ];

    const example = [
      '2024-01-15',
      'DSA',
      '5',
      '3',
      '120',
      'Solved array problems',
    ];

    return `${headers.join(',')}\n${example.join(',')}`;
  }

  /**
   * Get import statistics
   */
  async getImportStats(userId: string) {
    try {
      const [totalImported, lastImport] = await Promise.all([
        prisma.trackerEntry.count({
          where: { userId, source: 'import' },
        }),
        prisma.trackerEntry.findFirst({
          where: { userId, source: 'import' },
          orderBy: { createdAt: 'desc' },
        }),
      ]);

      log.info('Import stats fetched', { userId });

      return {
        totalImported,
        lastImport: lastImport?.createdAt || null,
      };
    } catch (error) {
      log.error('Error fetching import stats', { userId }, error);
      throw error;
    }
  }
}

export const trackerImportService = new TrackerImportService();
export default trackerImportService;