// ===== FILE: src/types/tracker.ts =====
// Complete tracker types matching Prisma schema

import type { PlatformCategory as PrismaPlatformCategory } from '@prisma/client';

// =============================================================================
// ENUMS & CONSTANTS
// =============================================================================

/** Entry source */
export type EntrySource = 'manual' | 'sync' | 'import' | 'api' | 'webhook';

/** Mood options */
export type Mood = 'great' | 'good' | 'okay' | 'tired' | 'frustrated';

/** Problem difficulty */
export type Difficulty = 'easy' | 'medium' | 'hard';

// =============================================================================
// CORE INTERFACES
// =============================================================================

/** Main tracker entry */
export interface TrackerEntry {
  id: string;
  userId: string;
  platformId?: string;
  customPlatformId?: string;
  
  // Date
  date: Date;
  
  // Classification
  category?: PrismaPlatformCategory;
  subcategory?: string;
  
  // Problem metrics
  problemsSolved: number;
  problemsAttempted: number;
  easyProblems: number;
  mediumProblems: number;
  hardProblems: number;
  
  // Code & Development
  commits: number;
  pullRequests: number;
  pullRequestsMerged: number;
  issuesOpened: number;
  issuesClosed: number;
  codeReviews: number;
  linesOfCode: number;
  
  // Projects
  projectsStarted: number;
  projectsCompleted: number;
  
  // Learning
  coursesStarted: number;
  coursesCompleted: number;
  lessonsCompleted: number;
  modulesCompleted: number;
  certificationsEarned: number;
  quizzesTaken: number;
  quizzesPassed: number;
  
  // Reading & Research
  articlesRead: number;
  tutorialsCompleted: number;
  documentationPages: number;
  
  // Jobs & Applications
  applicationsSubmitted: number;
  applicationsViewed: number;
  interviewsScheduled: number;
  interviewsCompleted: number;
  offersReceived: number;
  
  // Competitions
  contestsParticipated: number;
  contestsCompleted: number;
  hackathonsJoined: number;
  hackathonsCompleted: number;
  
  // Community
  mentoringSessions: number;
  helpGiven: number;
  helpReceived: number;
  postsWritten: number;
  commentsWritten: number;
  
  // Time
  timeSpent: number; // minutes
  focusTime: number; // minutes
  
  // Quality metrics
  averageDifficulty?: number;
  accuracyRate?: number;
  completionRate?: number;
  
  // Platform-specific
  rating?: number;
  ratingChange?: number;
  rank?: number;
  rankChange?: number;
  points?: number;
  pointsEarned?: number;
  streak?: number;
  xpEarned?: number;
  
  // Mood & Notes
  mood?: Mood;
  energyLevel?: number; // 1-5
  productivityRating?: number; // 1-5
  notes?: string;
  
  // Tags
  tags: string[];
  topics: string[];
  languages: string[];
  
  // Source
  source: EntrySource;
  syncLogId?: string;
  isAutoGenerated: boolean;
  
  // Verification
  isVerified: boolean;
  verifiedAt?: Date;
  
  // Custom fields
  customFields?: Record<string, unknown>;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  
  // Relations
  platform?: {
    id: string;
    slug: string;
    name: string;
    icon?: string;
    color?: string;
    category: PrismaPlatformCategory;
  };
}

/** Tracker entry input (for create/update) */
export interface TrackerEntryInput {
  date: string | Date;
  platformId?: string;
  customPlatformId?: string;
  category?: PrismaPlatformCategory;
  
  // Metrics
  problemsSolved?: number;
  problemsAttempted?: number;
  easyProblems?: number;
  mediumProblems?: number;
  hardProblems?: number;
  commits?: number;
  pullRequests?: number;
  pullRequestsMerged?: number;
  issuesOpened?: number;
  issuesClosed?: number;
  codeReviews?: number;
  linesOfCode?: number;
  projectsStarted?: number;
  projectsCompleted?: number;
  coursesStarted?: number;
  coursesCompleted?: number;
  lessonsCompleted?: number;
  modulesCompleted?: number;
  certificationsEarned?: number;
  applicationsSubmitted?: number;
  applicationsViewed?: number;
  interviewsScheduled?: number;
  interviewsCompleted?: number;
  offersReceived?: number;
  contestsParticipated?: number;
  hackathonsJoined?: number;
  timeSpent?: number;
  focusTime?: number;
  
  // Platform-specific
  rating?: number;
  ratingChange?: number;
  rank?: number;
  rankChange?: number;
  points?: number;
  pointsEarned?: number;
  
  // Mood & Notes
  mood?: Mood;
  energyLevel?: number;
  productivityRating?: number;
  notes?: string;
  
  // Tags
  tags?: string[];
  topics?: string[];
  languages?: string[];
  
  // Custom fields
  customFields?: Record<string, unknown>;
}

/** Daily stats (aggregated) */
export interface DailyStats {
  id: string;
  userId: string;
  date: Date;
  
  // Totals
  totalProblems: number;
  totalCommits: number;
  totalPullRequests: number;
  totalTimeSpent: number;
  totalPoints: number;
  
  // Breakdowns
  platformBreakdown?: Record<string, {
    problems: number;
    commits: number;
    time: number;
    points: number;
  }>;
  categoryBreakdown?: Record<string, number>;
  
  // Streak
  hadActivity: boolean;
  streakDay?: number;
  
  // Status
  isComplete: boolean;
  computedAt?: Date;
  
  createdAt: Date;
  updatedAt: Date;
}

/** Streak history */
export interface StreakHistory {
  id: string;
  userId: string;
  startDate: Date;
  endDate: Date;
  length: number;
  isActive: boolean;
  isCurrent: boolean;
  endReason?: 'natural' | 'broken' | 'freeze_used';
  totalProblems: number;
  totalCommits: number;
  createdAt: Date;
  updatedAt: Date;
}

/** Tracker summary */
export interface TrackerSummary {
  dateRange: {
    start: Date;
    end: Date;
    days: number;
  };
  totals: {
    problems: number;
    commits: number;
    pullRequests: number;
    time: number;
    points: number;
    entries: number;
  };
  averages: {
    problemsPerDay: number;
    commitsPerDay: number;
    timePerDay: number;
    pointsPerDay: number;
  };
  streaks: {
    current: number;
    longest: number;
    startDate?: Date;
  };
  byDifficulty: {
    easy: number;
    medium: number;
    hard: number;
  };
  byPlatform: Array<{
    platformId: string;
    platformName: string;
    entries: number;
    problems: number;
    commits: number;
  }>;
  byCategory: Array<{
    category: PrismaPlatformCategory;
    entries: number;
    problems: number;
    time: number;
  }>;
  activeDays: number;
  mostProductiveDay?: {
    date: Date;
    problems: number;
    time: number;
  };
  recentEntries: TrackerEntry[];
}

// =============================================================================
// FILTER & QUERY TYPES
// =============================================================================

/** Tracker filter options */
export interface TrackerFilter {
  startDate?: Date | string;
  endDate?: Date | string;
  platformIds?: string[];
  categories?: PrismaPlatformCategory[];
  source?: EntrySource;
  hasNotes?: boolean;
  minProblems?: number;
  maxProblems?: number;
  tags?: string[];
  topics?: string[];
  languages?: string[];
  search?: string;
}

/** Tracker sort options */
export interface TrackerSortOptions {
  field: 'date' | 'problemsSolved' | 'timeSpent' | 'points' | 'createdAt';
  order: 'asc' | 'desc';
}

/** Date range */
export interface DateRange {
  start: Date;
  end: Date;
}

// =============================================================================
// BULK OPERATIONS
// =============================================================================

/** Bulk update input */
export interface BulkUpdateInput {
  ids: string[];
  data: Partial<TrackerEntryInput>;
}

/** Bulk delete input */
export interface BulkDeleteInput {
  ids: string[];
}

/** Bulk operation result */
export interface BulkOperationResult {
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  errors?: Array<{
    id: string;
    error: string;
  }>;
}

// =============================================================================
// IMPORT/EXPORT TYPES
// =============================================================================

/** Import data format */
export interface TrackerImportData {
  entries: TrackerEntryInput[];
  options?: {
    skipDuplicates?: boolean;
    updateExisting?: boolean;
    defaultPlatform?: string;
  };
}

/** Import result */
export interface TrackerImportResult {
  success: boolean;
  total: number;
  imported: number;
  skipped: number;
  failed: number;
  errors?: Array<{
    row: number;
    error: string;
    data?: unknown;
  }>;
}

// =============================================================================
// DISPLAY CONFIGURATIONS
// =============================================================================

/** Mood configuration */
export const MOOD_CONFIG: Record<Mood, {
  label: string;
  emoji: string;
  color: string;
}> = {
  great: { label: 'Great', emoji: '😄', color: '#10B981' },
  good: { label: 'Good', emoji: '🙂', color: '#3B82F6' },
  okay: { label: 'Okay', emoji: '😐', color: '#F59E0B' },
  tired: { label: 'Tired', emoji: '😴', color: '#6B7280' },
  frustrated: { label: 'Frustrated', emoji: '😤', color: '#EF4444' },
};

/** Difficulty configuration */
export const DIFFICULTY_CONFIG: Record<Difficulty, {
  label: string;
  color: string;
  bgColor: string;
  points: number;
}> = {
  easy: { label: 'Easy', color: '#10B981', bgColor: '#D1FAE5', points: 1 },
  medium: { label: 'Medium', color: '#F59E0B', bgColor: '#FEF3C7', points: 2 },
  hard: { label: 'Hard', color: '#EF4444', bgColor: '#FEE2E2', points: 3 },
};

/** Entry source configuration */
export const SOURCE_CONFIG: Record<EntrySource, {
  label: string;
  icon: string;
  color: string;
}> = {
  manual: { label: 'Manual', icon: 'Edit', color: '#3B82F6' },
  sync: { label: 'Synced', icon: 'RefreshCw', color: '#10B981' },
  import: { label: 'Imported', icon: 'Upload', color: '#8B5CF6' },
  api: { label: 'API', icon: 'Code', color: '#F59E0B' },
  webhook: { label: 'Webhook', icon: 'Webhook', color: '#EC4899' },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/** Calculate total problems */
export function calculateTotalProblems(entry: TrackerEntry): number {
  return entry.easyProblems + entry.mediumProblems + entry.hardProblems;
}

/** Calculate weighted difficulty score */
export function calculateDifficultyScore(entry: TrackerEntry): number {
  return (
    entry.easyProblems * DIFFICULTY_CONFIG.easy.points +
    entry.mediumProblems * DIFFICULTY_CONFIG.medium.points +
    entry.hardProblems * DIFFICULTY_CONFIG.hard.points
  );
}

/** Get mood config */
export function getMoodConfig(mood: Mood) {
  return MOOD_CONFIG[mood];
}

/** Get difficulty config */
export function getDifficultyConfig(difficulty: Difficulty) {
  return DIFFICULTY_CONFIG[difficulty];
}

/** Format time spent */
export function formatTimeSpent(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
}

/** Check if entry has activity */
export function hasActivity(entry: TrackerEntry): boolean {
  return (
    entry.problemsSolved > 0 ||
    entry.commits > 0 ||
    entry.pullRequests > 0 ||
    entry.projectsCompleted > 0 ||
    entry.coursesCompleted > 0 ||
    entry.applicationsSubmitted > 0 ||
    entry.contestsParticipated > 0 ||
    entry.timeSpent > 0
  );
}

/** Get entry activity summary */
export function getActivitySummary(entry: TrackerEntry): string {
  const parts: string[] = [];
  if (entry.problemsSolved > 0) parts.push(`${entry.problemsSolved} problems`);
  if (entry.commits > 0) parts.push(`${entry.commits} commits`);
  if (entry.timeSpent > 0) parts.push(formatTimeSpent(entry.timeSpent));
  return parts.join(', ') || 'No activity';
}

/** Merge entries for same date */
export function mergeEntriesForDate(entries: TrackerEntry[]): TrackerEntry {
  if (entries.length === 0) throw new Error('No entries to merge');
  if (entries.length === 1) return entries[0];
  
  const base = { ...entries[0] };
  
  for (let i = 1; i < entries.length; i++) {
    const entry = entries[i];
    base.problemsSolved += entry.problemsSolved;
    base.problemsAttempted += entry.problemsAttempted;
    base.easyProblems += entry.easyProblems;
    base.mediumProblems += entry.mediumProblems;
    base.hardProblems += entry.hardProblems;
    base.commits += entry.commits;
    base.pullRequests += entry.pullRequests;
    base.timeSpent += entry.timeSpent;
    base.points = (base.points || 0) + (entry.points || 0);
  }
  
  return base;
}

/** Validate tracker entry input */
export function validateTrackerInput(input: TrackerEntryInput): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!input.date) {
    errors.push('Date is required');
  }
  
  const numericFields = [
    'problemsSolved', 'easyProblems', 'mediumProblems', 'hardProblems',
    'commits', 'pullRequests', 'timeSpent', 'points',
  ];
  
  for (const field of numericFields) {
    const value = input[field as keyof TrackerEntryInput];
    if (value !== undefined && (typeof value !== 'number' || value < 0)) {
      errors.push(`${field} must be a non-negative number`);
    }
  }
  
  if (input.energyLevel !== undefined && (input.energyLevel < 1 || input.energyLevel > 5)) {
    errors.push('Energy level must be between 1 and 5');
  }
  
  if (input.productivityRating !== undefined && (input.productivityRating < 1 || input.productivityRating > 5)) {
    errors.push('Productivity rating must be between 1 and 5');
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

export default TrackerEntry;