import { ACHIEVEMENT_THRESHOLDS } from "@/lib/constants"

export const achievementDefinitions = [
  {
    id: "first-steps",
    name: "First Steps",
    description: "Created your first tracker entry",
    icon: "🎯",
    threshold: ACHIEVEMENT_THRESHOLDS.FIRST_ENTRY,
    category: "general",
  },
  {
    id: "week-warrior",
    name: "Week Warrior",
    description: "Tracked for 7 consecutive days",
    icon: "🔥",
    threshold: ACHIEVEMENT_THRESHOLDS.WEEK_STREAK,
    category: "streak",
  },
  {
    id: "month-master",
    name: "Month Master",
    description: "Tracked for 30 consecutive days",
    icon: "📅",
    threshold: ACHIEVEMENT_THRESHOLDS.MONTH_STREAK,
    category: "streak",
  },
  {
    id: "century-club",
    name: "Century Club",
    description: "Solved 100 DSA problems",
    icon: "💯",
    threshold: ACHIEVEMENT_THRESHOLDS.PROBLEMS_100,
    category: "dsa",
  },
  {
    id: "problem-solver",
    name: "Problem Solver",
    description: "Solved 500 DSA problems",
    icon: "🧩",
    threshold: ACHIEVEMENT_THRESHOLDS.PROBLEMS_500,
    category: "dsa",
  },
  {
    id: "coding-machine",
    name: "Coding Machine",
    description: "Solved 1000 DSA problems",
    icon: "🤖",
    threshold: ACHIEVEMENT_THRESHOLDS.PROBLEMS_1000,
    category: "dsa",
  },
  {
    id: "job-hunter",
    name: "Job Hunter",
    description: "Applied to 50 jobs",
    icon: "🎯",
    threshold: ACHIEVEMENT_THRESHOLDS.JOBS_50,
    category: "jobs",
  },
  {
    id: "interview-pro",
    name: "Interview Pro",
    description: "Applied to 100 jobs",
    icon: "💼",
    threshold: ACHIEVEMENT_THRESHOLDS.JOBS_100,
    category: "jobs",
  },
  {
    id: "learning-enthusiast",
    name: "Learning Enthusiast",
    description: "Completed 5 courses",
    icon: "📚",
    threshold: ACHIEVEMENT_THRESHOLDS.COURSES_5,
    category: "learning",
  },
  {
    id: "learning-pro",
    name: "Learning Pro",
    description: "Completed 10 courses",
    icon: "🎓",
    threshold: ACHIEVEMENT_THRESHOLDS.COURSES_10,
    category: "learning",
  },
  {
    id: "hackathon-newbie",
    name: "Hackathon Newbie",
    description: "Participated in first hackathon",
    icon: "🏅",
    threshold: ACHIEVEMENT_THRESHOLDS.HACKATHONS_1,
    category: "hackathons",
  },
  {
    id: "hackathon-hero",
    name: "Hackathon Hero",
    description: "Participated in 10 hackathons",
    icon: "🏆",
    threshold: ACHIEVEMENT_THRESHOLDS.HACKATHONS_10,
    category: "hackathons",
  },
  {
    id: "git-champion",
    name: "Git Champion",
    description: "Made 100 GitHub commits",
    icon: "🐙",
    threshold: ACHIEVEMENT_THRESHOLDS.COMMITS_100,
    category: "development",
  },
  {
    id: "open-source-contributor",
    name: "Open Source Contributor",
    description: "Made 50 contributions",
    icon: "🌟",
    threshold: ACHIEVEMENT_THRESHOLDS.CONTRIBUTIONS_50,
    category: "development",
  },
  {
    id: "time-tracker",
    name: "Time Tracker",
    description: "Logged 100 hours of coding",
    icon: "⏰",
    threshold: ACHIEVEMENT_THRESHOLDS.HOURS_100,
    category: "general",
  },
]

export const achievementCategories = {
  general: { name: "General", color: "bg-blue-500" },
  streak: { name: "Streaks", color: "bg-orange-500" },
  dsa: { name: "DSA", color: "bg-purple-500" },
  jobs: { name: "Jobs", color: "bg-green-500" },
  learning: { name: "Learning", color: "bg-yellow-500" },
  hackathons: { name: "Hackathons", color: "bg-red-500" },
  development: { name: "Development", color: "bg-indigo-500" },
}