// src/config/platforms.ts

import { Platform, PlatformCategory } from '@/types/platform'

export const platforms: Platform[] = [
    // ========================================
    // DSA / COMPETITIVE PROGRAMMING (15)
    // ========================================
    {
        id: 'leetcode',
        name: 'LeetCode',
        slug: 'leetcode',
        category: 'dsa',
        displayName: 'LeetCode',
        icon: '/icons/leetcode.svg',
        color: '#FFA116',
        website: 'https://leetcode.com',
        authType: 'scraping', // GraphQL unofficial API
        supportsAutoSync: true,
        description: 'Practice coding problems and prepare for technical interviews',
        dataPoints: ['problems_solved', 'easy', 'medium', 'hard', 'contest_rating', 'streak', 'ranking'],
        setupInstructions: 'Enter your LeetCode username (e.g., username from https://leetcode.com/username/)',
    },
    {
        id: 'codeforces',
        name: 'Codeforces',
        slug: 'codeforces',
        category: 'dsa',
        displayName: 'Codeforces',
        icon: '/icons/codeforces.svg',
        color: '#1F8ACB',
        website: 'https://codeforces.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Competitive programming contests and practice',
        dataPoints: ['rating', 'max_rating', 'rank', 'contests', 'problems_solved', 'contributions'],
        setupInstructions: 'Enter your Codeforces handle (username)',
    },
    {
        id: 'codechef',
        name: 'CodeChef',
        slug: 'codechef',
        category: 'dsa',
        displayName: 'CodeChef',
        icon: '/icons/codechef.svg',
        color: '#5B4638',
        website: 'https://www.codechef.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Competitive programming and monthly contests',
        dataPoints: ['rating', 'stars', 'problems_solved', 'contests', 'global_rank', 'country_rank'],
        setupInstructions: 'Enter your CodeChef username',
    },
    {
        id: 'hackerrank',
        name: 'HackerRank',
        slug: 'hackerrank',
        category: 'dsa',
        displayName: 'HackerRank',
        icon: '/icons/hackerrank.svg',
        color: '#00EA64',
        website: 'https://www.hackerrank.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Coding challenges and skill certifications',
        dataPoints: ['badges', 'certificates', 'problems_solved', 'stars', 'rank'],
        setupInstructions: 'Enter your HackerRank username',
    },
    {
        id: 'hackerearth',
        name: 'HackerEarth',
        slug: 'hackerearth',
        category: 'dsa',
        displayName: 'HackerEarth',
        icon: '/icons/hackerearth.svg',
        color: '#2C3454',
        website: 'https://www.hackerearth.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Coding challenges and hackathons',
        dataPoints: ['problems_solved', 'contests', 'hackathons', 'rating'],
        setupInstructions: 'Enter your HackerEarth username',
    },
    {
        id: 'geeksforgeeks',
        name: 'GeeksforGeeks',
        slug: 'geeksforgeeks',
        category: 'dsa',
        displayName: 'GeeksforGeeks',
        icon: '/icons/gfg.svg',
        color: '#2F8D46',
        website: 'https://www.geeksforgeeks.org',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'DSA practice and computer science resources',
        dataPoints: ['problems_solved', 'coding_score', 'streak', 'institute_rank'],
        setupInstructions: 'Enter your GeeksforGeeks username',
    },
    {
        id: 'atcoder',
        name: 'AtCoder',
        slug: 'atcoder',
        category: 'dsa',
        displayName: 'AtCoder',
        icon: '/icons/atcoder.svg',
        color: '#222222',
        website: 'https://atcoder.jp',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Japanese competitive programming platform',
        dataPoints: ['rating', 'rank', 'contests', 'problems_solved', 'highest_rating'],
        setupInstructions: 'Enter your AtCoder username',
    },
    {
        id: 'spoj',
        name: 'SPOJ',
        slug: 'spoj',
        category: 'dsa',
        displayName: 'SPOJ',
        icon: '/icons/spoj.svg',
        color: '#0055A4',
        website: 'https://www.spoj.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Sphere Online Judge - classical problems',
        dataPoints: ['problems_solved', 'points', 'rank', 'submissions'],
        setupInstructions: 'Enter your SPOJ username',
    },
    {
        id: 'topcoder',
        name: 'TopCoder',
        slug: 'topcoder',
        category: 'dsa',
        displayName: 'TopCoder',
        icon: '/icons/topcoder.svg',
        color: '#29A8E0',
        website: 'https://www.topcoder.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Competitive programming and crowdsourcing',
        dataPoints: ['rating', 'rank', 'challenges_won', 'earnings', 'algorithm_rating'],
        setupInstructions: 'Enter your TopCoder handle',
    },
    {
    id: 'codingninjas',
    name: 'Coding Ninjas',
    slug: 'codingninjas',
    category: 'dsa',
    displayName: 'Coding Ninjas',
    icon: '/icons/codingninjas.svg',
    color: '#DD1F26',
    website: 'https://www.codingninjas.com',
    authType: 'manual',
    supportsAutoSync: false,
    description: 'India-focused DSA practice & structured courses',
    dataPoints: [
        'problems_solved',
        'courses_completed',
        'practice_sessions',
        'streak',
        'certificates'
    ],
    setupInstructions: 'Manually track Coding Ninjas progress (DSA sheets, courses, contests)',
},
    {
        id: 'codewars',
        name: 'Codewars',
        slug: 'codewars',
        category: 'dsa',
        displayName: 'Codewars',
        icon: '/icons/codewars.svg',
        color: '#B1361E',
        website: 'https://www.codewars.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Kata-based coding challenges',
        dataPoints: ['honor', 'rank', 'katas_completed', 'languages', 'leaderboard_position'],
        setupInstructions: 'Enter your Codewars username',
    },
    {
        id: 'exercism',
        name: 'Exercism',
        slug: 'exercism',
        category: 'dsa',
        displayName: 'Exercism',
        icon: '/icons/exercism.svg',
        color: '#009CAB',
        website: 'https://exercism.org',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Code practice and mentorship',
        dataPoints: ['exercises_completed', 'tracks', 'reputation', 'mentoring_sessions'],
        setupInstructions: 'Enter your Exercism username',
    },
    {
        id: 'projecteuler',
        name: 'Project Euler',
        slug: 'projecteuler',
        category: 'dsa',
        displayName: 'Project Euler',
        icon: '/icons/projecteuler.svg',
        color: '#4A4A4A',
        website: 'https://projecteuler.net',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Mathematical/computational problems',
        dataPoints: ['problems_solved', 'level', 'awards'],
        setupInstructions: 'Manually log problems solved',
    },
    {
        id: 'interviewbit',
        name: 'InterviewBit',
        slug: 'interviewbit',
        category: 'dsa',
        displayName: 'InterviewBit',
        icon: '/icons/interviewbit.svg',
        color: '#FF6B6B',
        website: 'https://www.interviewbit.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Interview preparation and practice',
        dataPoints: ['problems_solved', 'score', 'rank', 'streak'],
        setupInstructions: 'Enter your InterviewBit username',
    },
    {
        id: 'algoexpert',
        name: 'AlgoExpert',
        slug: 'algoexpert',
        category: 'dsa',
        displayName: 'AlgoExpert',
        icon: '/icons/algoexpert.svg',
        color: '#00A896',
        website: 'https://www.algoexpert.io',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Curated coding interview questions',
        dataPoints: ['questions_completed', 'assessments', 'certificates'],
        setupInstructions: 'Manually track completed questions',
    },
    {
        id: 'binarysearch',
        name: 'BinarySearch',
        slug: 'binarysearch',
        category: 'dsa',
        displayName: 'BinarySearch',
        icon: '/icons/binarysearch.svg',
        color: '#3B82F6',
        website: 'https://binarysearch.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Collaborative coding platform',
        dataPoints: ['problems_solved', 'rating', 'contests', 'rooms_joined'],
        setupInstructions: 'Enter your BinarySearch username',
    },

    // ========================================
    // JOB PORTALS (12)
    // ========================================
    {
        id: 'linkedin',
        name: 'LinkedIn',
        slug: 'linkedin',
        category: 'job',
        displayName: 'LinkedIn',
        icon: '/icons/linkedin.svg',
        color: '#0A66C2',
        website: 'https://www.linkedin.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Professional networking and job search',
        dataPoints: ['applications_sent', 'profile_views', 'connections', 'posts', 'engagement'],
        setupInstructions: 'Click "Connect with LinkedIn" to authorize access',
    },
    {
        id: 'indeed',
        name: 'Indeed',
        slug: 'indeed',
        category: 'job',
        displayName: 'Indeed',
        icon: '/icons/indeed.svg',
        color: '#2164F3',
        website: 'https://www.indeed.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Global job search platform',
        dataPoints: ['applications_sent', 'saved_jobs', 'interviews', 'responses'],
        setupInstructions: 'Manually log job applications from Indeed',
    },
    {
        id: 'glassdoor',
        name: 'Glassdoor',
        slug: 'glassdoor',
        category: 'job',
        displayName: 'Glassdoor',
        icon: '/icons/glassdoor.svg',
        color: '#0CAA41',
        website: 'https://www.glassdoor.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Company reviews and job search',
        dataPoints: ['applications_sent', 'reviews_read', 'saved_jobs', 'company_follows'],
        setupInstructions: 'Manually track Glassdoor applications',
    },
    {
        id: 'naukri',
        name: 'Naukri',
        slug: 'naukri',
        category: 'job',
        displayName: 'Naukri.com',
        icon: '/icons/naukri.svg',
        color: '#4A90D9',
        website: 'https://www.naukri.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'India\'s leading job portal',
        dataPoints: ['applications_sent', 'profile_views', 'recruiter_calls', 'profile_score'],
        setupInstructions: 'Enter your Naukri.com registered email',
    },
    {
        id: 'wellfound',
        name: 'Wellfound',
        slug: 'wellfound',
        category: 'job',
        displayName: 'Wellfound (AngelList)',
        icon: '/icons/angellist.svg',
        color: '#000000',
        website: 'https://wellfound.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Startup jobs and investments',
        dataPoints: ['applications_sent', 'matches', 'saved_jobs', 'intro_requests'],
        setupInstructions: 'Connect with Wellfound account',
    },
    {
        id: 'internshala',
        name: 'Internshala',
        slug: 'internshala',
        category: 'job',
        displayName: 'Internshala',
        icon: '/icons/internshala.svg',
        color: '#00A5EC',
        website: 'https://internshala.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Internships and fresher jobs in India',
        dataPoints: ['applications_sent', 'certifications', 'trainings', 'interviews'],
        setupInstructions: 'Enter Internshala credentials for data sync',
    },
    {
        id: 'monster',
        name: 'Monster',
        slug: 'monster',
        category: 'job',
        displayName: 'Monster',
        icon: '/icons/monster.svg',
        color: '#6E45A5',
        website: 'https://www.monster.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Global employment website',
        dataPoints: ['applications_sent', 'profile_views', 'saved_jobs'],
        setupInstructions: 'Manually log Monster applications',
    },
    {
        id: 'hired',
        name: 'Hired',
        slug: 'hired',
        category: 'job',
        displayName: 'Hired',
        icon: '/icons/hired.svg',
        color: '#2B6FBA',
        website: 'https://hired.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Tech job marketplace',
        dataPoints: ['interview_requests', 'offers', 'salary_bids', 'company_views'],
        setupInstructions: 'Authorize Hired to share job activity',
    },
    {
        id: 'dice',
        name: 'Dice',
        slug: 'dice',
        category: 'job',
        displayName: 'Dice',
        icon: '/icons/dice.svg',
        color: '#EB1C24',
        website: 'https://www.dice.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Tech-focused job board',
        dataPoints: ['applications_sent', 'profile_views', 'saved_searches'],
        setupInstructions: 'Manually track Dice applications',
    },
    {
        id: 'simplyhired',
        name: 'SimplyHired',
        slug: 'simplyhired',
        category: 'job',
        displayName: 'SimplyHired',
        icon: '/icons/simplyhired.svg',
        color: '#5A67D8',
        website: 'https://www.simplyhired.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Job search engine',
        dataPoints: ['applications_sent', 'saved_jobs'],
        setupInstructions: 'Manually log applications',
    },
    {
        id: 'ziprecruiter',
        name: 'ZipRecruiter',
        slug: 'ziprecruiter',
        category: 'job',
        displayName: 'ZipRecruiter',
        icon: '/icons/ziprecruiter.svg',
        color: '#1C68D4',
        website: 'https://www.ziprecruiter.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Job matching technology',
        dataPoints: ['applications_sent', 'job_matches', 'interview_invites'],
        setupInstructions: 'Manually track ZipRecruiter activity',
    },
    {
        id: 'instahyre',
        name: 'Instahyre',
        slug: 'instahyre',
        category: 'job',
        displayName: 'Instahyre',
        icon: '/icons/instahyre.svg',
        color: '#FF6B35',
        website: 'https://www.instahyre.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'AI-powered job matching for tech professionals',
        dataPoints: ['applications_sent', 'interview_requests', 'offers', 'profile_strength'],
        setupInstructions: 'Enter Instahyre login credentials',
    },

    // ========================================
    // HACKATHONS & COMPETITIONS (10)
    // ========================================
    {
        id: 'devpost',
        name: 'Devpost',
        slug: 'devpost',
        category: 'hackathon',
        displayName: 'Devpost',
        icon: '/icons/devpost.svg',
        color: '#003E54',
        website: 'https://devpost.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Hackathon discovery and project showcase',
        dataPoints: ['hackathons_participated', 'projects', 'achievements', 'wins', 'likes'],
        setupInstructions: 'Connect your Devpost account',
    },
    {
        id: 'devfolio',
        name: 'Devfolio',
        slug: 'devfolio',
        category: 'hackathon',
        displayName: 'Devfolio',
        icon: '/icons/devfolio.svg',
        color: '#3770FF',
        website: 'https://devfolio.co',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Indian hackathon platform',
        dataPoints: ['hackathons_participated', 'projects', 'wins', 'submissions'],
        setupInstructions: 'Authorize Devfolio access',
    },
    {
        id: 'mlh',
        name: 'MLH',
        slug: 'mlh',
        category: 'hackathon',
        displayName: 'Major League Hacking',
        icon: '/icons/mlh.svg',
        color: '#E73427',
        website: 'https://mlh.io',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Student hackathon league',
        dataPoints: ['hackathons_participated', 'season_points', 'badges', 'rank'],
        setupInstructions: 'Connect with MLH account',
    },
    {
        id: 'unstop',
        name: 'Unstop',
        slug: 'unstop',
        category: 'hackathon',
        displayName: 'Unstop (D2C)',
        icon: '/icons/unstop.svg',
        color: '#0073E6',
        website: 'https://unstop.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Competitions, hackathons, and hiring challenges',
        dataPoints: ['competitions', 'hackathons', 'quizzes', 'certificates', 'xp_points'],
        setupInstructions: 'Enter Unstop username',
    },
    {
        id: 'kaggle',
        name: 'Kaggle',
        slug: 'kaggle',
        category: 'hackathon',
        displayName: 'Kaggle',
        icon: '/icons/kaggle.svg',
        color: '#20BEFF',
        website: 'https://www.kaggle.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Data science competitions and datasets',
        dataPoints: ['competitions', 'medals', 'tier', 'notebooks', 'datasets', 'ranking'],
        setupInstructions: 'Enter your Kaggle username',
    },
    {
        id: 'dribbble',
        name: 'Dribbble',
        slug: 'dribbble',
        category: 'hackathon',
        displayName: 'Dribbble',
        icon: '/icons/dribbble.svg',
        color: '#EA4C89',
        website: 'https://dribbble.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Design portfolio and community',
        dataPoints: ['shots', 'likes', 'followers', 'projects', 'views'],
        setupInstructions: 'Connect Dribbble account',
    },
    {
        id: 'behance',
        name: 'Behance',
        slug: 'behance',
        category: 'hackathon',
        displayName: 'Behance',
        icon: '/icons/behance.svg',
        color: '#1769FF',
        website: 'https://www.behance.net',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Creative portfolio showcase',
        dataPoints: ['projects', 'appreciations', 'followers', 'views', 'comments'],
        setupInstructions: 'Authorize Behance access',
    },
    {
        id: 'producthunt',
        name: 'Product Hunt',
        slug: 'producthunt',
        category: 'hackathon',
        displayName: 'Product Hunt',
        icon: '/icons/producthunt.svg',
        color: '#DA552F',
        website: 'https://www.producthunt.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Product launches and discovery',
        dataPoints: ['products_launched', 'upvotes', 'followers', 'collections'],
        setupInstructions: 'Connect Product Hunt account',
    },
    {
        id: 'hackathoncom',
        name: 'Hackathon.com',
        slug: 'hackathoncom',
        category: 'hackathon',
        displayName: 'Hackathon.com',
        icon: '/icons/hackathon.svg',
        color: '#FF4F00',
        website: 'https://www.hackathon.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Discover and participate in hackathons worldwide',
        dataPoints: ['hackathons_participated', 'projects_submitted', 'awards'],
        setupInstructions: 'Enter your Hackathon.com username',
    },
    {
        id: 'codingame',
        name: 'CodinGame',
        slug: 'codingame',
        category: 'hackathon',
        displayName: 'CodinGame',
        icon: '/icons/codingame.svg',
        color: '#F2BB13',
        website: 'https://www.codingame.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Game-based coding challenges and competitions',
        dataPoints: ['level', 'xp', 'achievements', 'clash_of_code', 'challenges_completed'],
        setupInstructions: 'Enter CodinGame username',
    },

    // ========================================
    // GIT / VERSION CONTROL (4)
    // ========================================
    {
        id: 'github',
        name: 'GitHub',
        slug: 'github',
        category: 'git',
        displayName: 'GitHub',
        icon: '/icons/github.svg',
        color: '#181717',
        website: 'https://github.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Code hosting and collaboration',
        dataPoints: ['repositories', 'commits', 'pull_requests', 'issues', 'stars', 'contributions', 'streak', 'followers'],
        setupInstructions: 'Click "Connect with GitHub" to authorize',
    },
    {
        id: 'gitlab',
        name: 'GitLab',
        slug: 'gitlab',
        category: 'git',
        displayName: 'GitLab',
        icon: '/icons/gitlab.svg',
        color: '#FC6D26',
        website: 'https://gitlab.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'DevOps platform',
        dataPoints: ['repositories', 'commits', 'merge_requests', 'pipelines', 'issues'],
        setupInstructions: 'Authorize GitLab access',
    },
    {
        id: 'bitbucket',
        name: 'Bitbucket',
        slug: 'bitbucket',
        category: 'git',
        displayName: 'Bitbucket',
        icon: '/icons/bitbucket.svg',
        color: '#0052CC',
        website: 'https://bitbucket.org',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Git repository management',
        dataPoints: ['repositories', 'commits', 'pull_requests', 'branches'],
        setupInstructions: 'Connect Bitbucket account',
    },
    {
        id: 'sourceforge',
        name: 'SourceForge',
        slug: 'sourceforge',
        category: 'git',
        displayName: 'SourceForge',
        icon: '/icons/sourceforge.svg',
        color: '#FF6600',
        website: 'https://sourceforge.net',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Open source software hosting',
        dataPoints: ['projects', 'downloads', 'reviews'],
        setupInstructions: 'Manually track SourceForge projects',
    },

    // ========================================
    // LEARNING PLATFORMS (12)
    // ========================================
    {
        id: 'coursera',
        name: 'Coursera',
        slug: 'coursera',
        category: 'learning',
        displayName: 'Coursera',
        icon: '/icons/coursera.svg',
        color: '#0056D2',
        website: 'https://www.coursera.org',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Online courses from top universities',
        dataPoints: ['courses_completed', 'certificates', 'specializations', 'hours_spent', 'grades'],
        setupInstructions: 'Connect your Coursera account',
    },
    {
        id: 'udemy',
        name: 'Udemy',
        slug: 'udemy',
        category: 'learning',
        displayName: 'Udemy',
        icon: '/icons/udemy.svg',
        color: '#A435F0',
        website: 'https://www.udemy.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Online learning marketplace',
        dataPoints: ['courses_enrolled', 'courses_completed', 'certificates', 'hours_spent'],
        setupInstructions: 'Manually log Udemy course progress',
    },
    {
        id: 'edx',
        name: 'edX',
        slug: 'edx',
        category: 'learning',
        displayName: 'edX',
        icon: '/icons/edx.svg',
        color: '#02262B',
        website: 'https://www.edx.org',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'University-level online courses',
        dataPoints: ['courses_completed', 'certificates', 'programs', 'verified_certificates'],
        setupInstructions: 'Authorize edX access',
    },
    {
        id: 'pluralsight',
        name: 'Pluralsight',
        slug: 'pluralsight',
        category: 'learning',
        displayName: 'Pluralsight',
        icon: '/icons/pluralsight.svg',
        color: '#F15B2A',
        website: 'https://www.pluralsight.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Technology skills platform',
        dataPoints: ['courses_completed', 'skill_iq', 'role_iq', 'hours_spent', 'paths'],
        setupInstructions: 'Enter Pluralsight API key or username',
    },
    {
        id: 'linkedinlearning',
        name: 'LinkedIn Learning',
        slug: 'linkedinlearning',
        category: 'learning',
        displayName: 'LinkedIn Learning',
        icon: '/icons/linkedinlearning.svg',
        color: '#0A66C2',
        website: 'https://www.linkedin.com/learning',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Professional development courses',
        dataPoints: ['courses_completed', 'certificates', 'hours_spent', 'skills', 'learning_paths'],
        setupInstructions: 'Connect with LinkedIn account',
    },
    {
        id: 'freecodecamp',
        name: 'freeCodeCamp',
        slug: 'freecodecamp',
        category: 'learning',
        displayName: 'freeCodeCamp',
        icon: '/icons/freecodecamp.svg',
        color: '#0A0A23',
        website: 'https://www.freecodecamp.org',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Free coding curriculum and certifications',
        dataPoints: ['certifications', 'challenges_completed', 'points', 'streak'],
        setupInstructions: 'Enter freeCodeCamp username',
    },
    {
        id: 'codecademy',
        name: 'Codecademy',
        slug: 'codecademy',
        category: 'learning',
        displayName: 'Codecademy',
        icon: '/icons/codecademy.svg',
        color: '#1F4056',
        website: 'https://www.codecademy.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Interactive coding lessons',
        dataPoints: ['courses_completed', 'badges', 'streak', 'skills', 'projects'],
        setupInstructions: 'Enter Codecademy username',
    },
    {
        id: 'udacity',
        name: 'Udacity',
        slug: 'udacity',
        category: 'learning',
        displayName: 'Udacity',
        icon: '/icons/udacity.svg',
        color: '#02B3E4',
        website: 'https://www.udacity.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Nanodegree programs for tech careers',
        dataPoints: ['nanodegrees', 'courses_completed', 'projects', 'reviews'],
        setupInstructions: 'Authorize Udacity access',
    },
    {
        id: 'skillshare',
        name: 'Skillshare',
        slug: 'skillshare',
        category: 'learning',
        displayName: 'Skillshare',
        icon: '/icons/skillshare.svg',
        color: '#00FF84',
        website: 'https://www.skillshare.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Creative and business classes',
        dataPoints: ['classes_taken', 'projects', 'minutes_watched', 'following'],
        setupInstructions: 'Manually log Skillshare courses',
    },
    {
        id: 'khanacademy',
        name: 'Khan Academy',
        slug: 'khanacademy',
        category: 'learning',
        displayName: 'Khan Academy',
        icon: '/icons/khanacademy.svg',
        color: '#14BF96',
        website: 'https://www.khanacademy.org',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'Free educational content',
        dataPoints: ['courses_completed', 'mastery_points', 'badges', 'streak', 'energy_points'],
        setupInstructions: 'Connect Khan Academy account',
    },
    {
        id: 'datacamp',
        name: 'DataCamp',
        slug: 'datacamp',
        category: 'learning',
        displayName: 'DataCamp',
        icon: '/icons/datacamp.svg',
        color: '#03EF62',
        website: 'https://www.datacamp.com',
        authType: 'api',
        supportsAutoSync: true,
        description: 'Data science and analytics courses',
        dataPoints: ['courses_completed', 'xp', 'certifications', 'tracks', 'skills'],
        setupInstructions: 'Enter DataCamp username',
    },
    {
        id: 'scrimba',
        name: 'Scrimba',
        slug: 'scrimba',
        category: 'learning',
        displayName: 'Scrimba',
        icon: '/icons/scrimba.svg',
        color: '#2B283A',
        website: 'https://scrimba.com',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Interactive coding courses',
        dataPoints: ['courses_completed', 'certificates', 'projects', 'screencasts_watched'],
        setupInstructions: 'Enter Scrimba username',
    },// ========================================
    // OPEN SOURCE PROGRAMS (8)
    // ========================================
    {
        id: 'gsoc',
        name: 'Google Summer of Code',
        slug: 'gsoc',
        category: 'opensource',
        displayName: 'GSoC',
        icon: '/icons/google.svg',
        color: '#4285F4',
        website: 'https://summerofcode.withgoogle.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Google open source internship program',
        dataPoints: ['applications', 'projects', 'mentorship_hours', 'status', 'year'],
        setupInstructions: 'Manually log GSoC participation',
    },
    {
        id: 'outreachy',
        name: 'Outreachy',
        slug: 'outreachy',
        category: 'opensource',
        displayName: 'Outreachy',
        icon: '/icons/outreachy.svg',
        color: '#5E4B8B',
        website: 'https://www.outreachy.org',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Diversity internships in open source',
        dataPoints: ['applications', 'contributions', 'status', 'round'],
        setupInstructions: 'Track Outreachy applications manually',
    },
    {
        id: 'lfx',
        name: 'LFX Mentorship',
        slug: 'lfx',
        category: 'opensource',
        displayName: 'LFX Mentorship',
        icon: '/icons/lfx.svg',
        color: '#0094FF',
        website: 'https://lfx.linuxfoundation.org/tools/mentorship',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Linux Foundation mentorship program',
        dataPoints: ['applications', 'projects', 'status', 'term'],
        setupInstructions: 'Manually track LFX applications',
    },
    {
        id: 'gssoc',
        name: 'GirlScript Summer of Code',
        slug: 'gssoc',
        category: 'opensource',
        displayName: 'GSSoC',
        icon: '/icons/gssoc.svg',
        color: '#FF7A59',
        website: 'https://gssoc.girlscript.tech',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'Open source program for beginners',
        dataPoints: ['contributions', 'prs_merged', 'points', 'rank', 'badges'],
        setupInstructions: 'Enter GSSoC username',
    },
    {
        id: 'hacktoberfest',
        name: 'Hacktoberfest',
        slug: 'hacktoberfest',
        category: 'opensource',
        displayName: 'Hacktoberfest',
        icon: '/icons/hacktoberfest.svg',
        color: '#FF8AE2',
        website: 'https://hacktoberfest.com',
        authType: 'oauth',
        supportsAutoSync: true,
        description: 'DigitalOcean s annual open source celebration',
        dataPoints: ['prs_submitted', 'prs_accepted', 'completion_status', 'year'],
        setupInstructions: 'Connect GitHub account for Hacktoberfest tracking',
    },
    {
        id: 'mlhfellowship',
        name: 'MLH Fellowship',
        slug: 'mlhfellowship',
        category: 'opensource',
        displayName: 'MLH Fellowship',
        icon: '/icons/mlh.svg',
        color: '#E73427',
        website: 'https://fellowship.mlh.io',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Remote internship alternative',
        dataPoints: ['applications', 'projects', 'status', 'pod'],
        setupInstructions: 'Manually log MLH Fellowship participation',
    },
    {
        id: 'swoc',
        name: 'Social Winter of Code',
        slug: 'swoc',
        category: 'opensource',
        displayName: 'SWoC',
        icon: '/icons/swoc.svg',
        color: '#FF6B6B',
        website: 'https://swoc.scriptindia.org',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Winter open source program',
        dataPoints: ['contributions', 'prs', 'points', 'certificates'],
        setupInstructions: 'Track SWoC contributions manually',
    },
    {
        id: 'kwoc',
        name: 'Kharagpur Winter of Code',
        slug: 'kwoc',
        category: 'opensource',
        displayName: 'KWoC',
        icon: '/icons/kwoc.svg',
        color: '#4A90E2',
        website: 'https://kwoc.kossiitkgp.org',
        authType: 'scraping',
        supportsAutoSync: true,
        description: 'IIT Kharagpurs open source program',
        dataPoints: ['contributions', 'prs', 'commits', 'projects'],
        setupInstructions: 'Enter KWoC username',
    },// ========================================
    // COMPANY-SPECIFIC PLATFORMS (6)
    // ========================================
    {
        id: 'amazonjobs',
        name: 'Amazon Jobs',
        slug: 'amazonjobs',
        category: 'company',
        displayName: 'Amazon Careers',
        icon: '/icons/amazon.svg',
        color: '#FF9900',
        website: 'https://www.amazon.jobs',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Amazon career opportunities',
        dataPoints: ['applications', 'interviews', 'status', 'positions_applied'],
        setupInstructions: 'Manually track Amazon applications',
    },
    {
        id: 'microsoftcareers',
        name: 'Microsoft Careers',
        slug: 'microsoftcareers',
        category: 'company',
        displayName: 'Microsoft Careers',
        icon: '/icons/microsoft.svg',
        color: '#00A4EF',
        website: 'https://careers.microsoft.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Microsoft job opportunities',
        dataPoints: ['applications', 'interviews', 'status', 'roles'],
        setupInstructions: 'Manually log Microsoft applications',
    },
    {
        id: 'googlecareers',
        name: 'Google Careers',
        slug: 'googlecareers',
        category: 'company',
        displayName: 'Google Careers',
        icon: '/icons/google.svg',
        color: '#4285F4',
        website: 'https://careers.google.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Google job opportunities',
        dataPoints: ['applications', 'interviews', 'status', 'referrals'],
        setupInstructions: 'Track Google applications manually',
    },
    {
        id: 'ibmcareers',
        name: 'IBM Careers',
        slug: 'ibmcareers',
        category: 'company',
        displayName: 'IBM Careers',
        icon: '/icons/ibm.svg',
        color: '#0530AD',
        website: 'https://www.ibm.com/careers',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'IBM job opportunities',
        dataPoints: ['applications', 'interviews', 'status'],
        setupInstructions: 'Manually track IBM applications',
    },
    {
        id: 'metacareers',
        name: 'Meta Careers',
        slug: 'metacareers',
        category: 'company',
        displayName: 'Meta Careers',
        icon: '/icons/meta.svg',
        color: '#0081FB',
        website: 'https://www.metacareers.com',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Meta job opportunities',
        dataPoints: ['applications', 'interviews', 'status', 'recruiter_calls'],
        setupInstructions: 'Manually log Meta applications',
    },
    {
        id: 'applecareers',
        name: 'Apple Careers',
        slug: 'applecareers',
        category: 'company',
        displayName: 'Apple Careers',
        icon: '/icons/apple.svg',
        color: '#000000',
        website: 'https://www.apple.com/careers',
        authType: 'manual',
        supportsAutoSync: false,
        description: 'Apple job opportunities',
        dataPoints: ['applications', 'interviews', 'status'],
        setupInstructions: 'Track Apple applications manually',
    },
]// ========================================
// CATEGORIES CONFIGURATION
// ========================================
export const categories: PlatformCategory[] = [
    {
        id: 'dsa',
        name: 'DSA & Competitive Programming',
        slug: 'dsa',
        description: 'Coding practice and competitive programming platforms',
        icon: 'Code',
        color: '#6366f1',
        order: 1,
    },
    {
        id: 'job',
        name: 'Job Portals',
        slug: 'job',
        description: 'Job search and career platforms',
        icon: 'Briefcase',
        color: '#10b981',
        order: 2,
    },
    {
        id: 'hackathon',
        name: 'Hackathons & Competitions',
        slug: 'hackathon',
        description: 'Hackathons, design challenges, and competitions',
        icon: 'Trophy',
        color: '#f59e0b',
        order: 3,
    },
    {
        id: 'git',
        name: 'Version Control',
        slug: 'git',
        description: 'Git repositories and version control platforms',
        icon: 'GitBranch',
        color: '#8b5cf6',
        order: 4,
    },
    {
        id: 'learning',
        name: 'Learning Platforms',
        slug: 'learning',
        description: 'Online courses and educational platforms',
        icon: 'GraduationCap',
        color: '#ec4899',
        order: 5,
    },
    {
        id: 'opensource',
        name: 'Open Source Programs',
        slug: 'opensource',
        description: 'Open source contribution programs',
        icon: 'Heart',
        color: '#ef4444',
        order: 6,
    },
    {
        id: 'company',
        name: 'Company Portals',
        slug: 'company',
        description: 'Direct company career pages',
        icon: 'Building',
        color: '#64748b',
        order: 7,
    },
]/// ========================================
// HELPER FUNCTIONS (CATEGORY FILTERS)
// ========================================

/**
 * Get all platforms in a specific category
 */
export function getPlatformsByCategory(categoryId: string): Platform[] {
    return platforms.filter(platform => platform.category === categoryId)
}

/**
 * Get a platform by its slug
 */
export function getPlatformBySlug(slug: string): Platform | undefined {
    return platforms.find(platform => platform.slug === slug)
}

/**
 * Get a platform by its ID
 */
export function getPlatformById(id: string): Platform | undefined {
    return platforms.find(platform => platform.id === id)
}

/**
 * Get all platforms that support auto-sync
 */
export function getAutoSyncablePlatforms(): Platform[] {
    return platforms.filter(platform => platform.supportsAutoSync)
}

/**
 * Get all OAuth-based platforms
 */
export function getOAuthPlatforms(): Platform[] {
    return platforms.filter(platform => platform.authType === 'oauth')
}

/**
 * Get category details by ID
 */
export function getCategoryById(id: string): PlatformCategory | undefined {
    return categories.find(category => category.id === id)
}

/**
 * Get all platforms grouped by category
 */
export function getPlatformsGroupedByCategory(): Record<string, Platform[]> {
    return categories.reduce((acc, category) => {
        acc[category.id] = getPlatformsByCategory(category.id)
        return acc
    }, {} as Record<string, Platform[]>)
}

/**
 * Get total count of platforms in a specific category
 */
export function getPlatformCountByCategory(categoryId: string): number {
    return getPlatformsByCategory(categoryId).length
}

/**
 * Get total number of platforms
 */
export function getTotalPlatformCount(): number {
    return platforms.length
}




// ========================================
// PLATFORM COUNTS BY CATEGORY
// ========================================
export const platformCounts = {
    dsa: platforms.filter(p => p.category === 'dsa').length,           // 15
    job: platforms.filter(p => p.category === 'job').length,           // 12
    hackathon: platforms.filter(p => p.category === 'hackathon').length, // 10
    git: platforms.filter(p => p.category === 'git').length,           // 4
    learning: platforms.filter(p => p.category === 'learning').length, // 12
    opensource: platforms.filter(p => p.category === 'opensource').length, // 8
    company: platforms.filter(p => p.category === 'company').length,   // 6
    total: platforms.length, // 67 platforms
}
export default platforms;